-- Run once in Supabase SQL Editor.
-- Public product images are readable by the Rates/Prices pages.
-- Only the White Saffron admin account can add, replace, or remove them.

create table if not exists public.item_photos (
  id bigint generated by default as identity primary key,
  item_key text not null unique,
  item_name text not null,
  photo_path text not null,
  updated_by uuid not null,
  updated_at timestamptz not null default now(),
  constraint item_photos_item_key_not_blank check (length(trim(item_key)) > 0),
  constraint item_photos_item_name_not_blank check (length(trim(item_name)) > 0)
);

alter table public.item_photos enable row level security;
grant select on public.item_photos to anon, authenticated;
grant insert, update, delete on public.item_photos to authenticated;
grant usage, select on sequence public.item_photos_id_seq to authenticated;

drop policy if exists "Public can view item photos" on public.item_photos;
create policy "Public can view item photos"
on public.item_photos for select
to anon, authenticated
using (true);

drop policy if exists "Admin can add item photos" on public.item_photos;
create policy "Admin can add item photos"
on public.item_photos for insert
to authenticated
with check (
  (select auth.uid()) = '5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid
  and updated_by = (select auth.uid())
);

drop policy if exists "Admin can update item photos" on public.item_photos;
create policy "Admin can update item photos"
on public.item_photos for update
to authenticated
using ((select auth.uid()) = '5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid)
with check (
  (select auth.uid()) = '5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid
  and updated_by = (select auth.uid())
);

drop policy if exists "Admin can delete item photos" on public.item_photos;
create policy "Admin can delete item photos"
on public.item_photos for delete
to authenticated
using ((select auth.uid()) = '5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'item-photos',
  'item-photos',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admin can view item photo objects" on storage.objects;
create policy "Admin can view item photo objects"
on storage.objects for select
to authenticated
using (
  bucket_id = 'item-photos'
  and (select auth.uid()) = '5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid
);

drop policy if exists "Admin can upload item photo objects" on storage.objects;
create policy "Admin can upload item photo objects"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'item-photos'
  and (select auth.uid()) = '5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid
);

drop policy if exists "Admin can update item photo objects" on storage.objects;
create policy "Admin can update item photo objects"
on storage.objects for update
to authenticated
using (
  bucket_id = 'item-photos'
  and (select auth.uid()) = '5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid
)
with check (
  bucket_id = 'item-photos'
  and (select auth.uid()) = '5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid
);

drop policy if exists "Admin can delete item photo objects" on storage.objects;
create policy "Admin can delete item photo objects"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'item-photos'
  and (select auth.uid()) = '5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid
);
