-- White Saffron Supply Rates setup
-- Run in Supabase project tmupbruwmwlrmewhoodn SQL Editor.

create table if not exists public.supply_rates (
  id bigint generated by default as identity primary key,
  vendor text not null,
  item_code text,
  item_name text not null,
  uom text not null default 'PCS',
  quantity numeric(14,3) not null default 1 check (quantity > 0),
  unit_rate numeric(14,4) not null check (unit_rate >= 0),
  gst_rate numeric(6,3) not null default 8 check (gst_rate >= 0),
  gst_mode text not null default 'exclusive' check (gst_mode in ('exclusive','inclusive','none')),
  net_amount numeric(14,2) generated always as (
    round((quantity * case when gst_mode='inclusive' then unit_rate/(1+gst_rate/100) else unit_rate end)::numeric,2)
  ) stored,
  gst_amount numeric(14,2) generated always as (
    round((case when gst_mode='none' then 0 when gst_mode='inclusive' then quantity*unit_rate-(quantity*unit_rate/(1+gst_rate/100)) else quantity*unit_rate*gst_rate/100 end)::numeric,2)
  ) stored,
  final_amount numeric(14,2) generated always as (
    round((case when gst_mode='exclusive' then quantity*unit_rate*(1+gst_rate/100) else quantity*unit_rate end)::numeric,2)
  ) stored,
  invoice_no text,
  invoice_date date,
  notes text,
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists supply_rates_vendor_item_idx on public.supply_rates (vendor, item_name, created_at desc);
create index if not exists supply_rates_created_by_idx on public.supply_rates (created_by, created_at desc);
alter table public.supply_rates enable row level security;

revoke all on table public.supply_rates from anon;
grant select, insert, update, delete on table public.supply_rates to authenticated;
grant usage, select on sequence public.supply_rates_id_seq to authenticated;

drop policy if exists "Supply rates authorized read" on public.supply_rates;
drop policy if exists "Supply rates authorized insert" on public.supply_rates;
drop policy if exists "Supply rates authorized update" on public.supply_rates;
drop policy if exists "Supply rates authorized delete" on public.supply_rates;

create policy "Supply rates authorized read" on public.supply_rates for select to authenticated
using ((select auth.uid()) in ('79c4c15e-87b7-415a-82f0-825054458e59'::uuid,'5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid));
create policy "Supply rates authorized insert" on public.supply_rates for insert to authenticated
with check ((select auth.uid()) in ('79c4c15e-87b7-415a-82f0-825054458e59'::uuid,'5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid) and created_by=(select auth.uid()));
create policy "Supply rates authorized update" on public.supply_rates for update to authenticated
using ((select auth.uid()) in ('79c4c15e-87b7-415a-82f0-825054458e59'::uuid,'5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid))
with check ((select auth.uid()) in ('79c4c15e-87b7-415a-82f0-825054458e59'::uuid,'5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid));
create policy "Supply rates authorized delete" on public.supply_rates for delete to authenticated
using ((select auth.uid())='5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid);
