-- White Saffron Inventory and Low-Supply Alerts
-- Run once in the Supabase SQL Editor.
create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  item_name text not null unique,
  unit text not null default 'PCS',
  current_quantity numeric not null default 0 check (current_quantity >= 0),
  minimum_quantity numeric not null default 0 check (minimum_quantity >= 0),
  enabled boolean not null default true,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.inventory_items enable row level security;
grant select, insert, update, delete on table public.inventory_items to authenticated;
grant usage, select on sequence public.inventory_items_id_seq to authenticated;
drop policy if exists "inventory_admin_select" on public.inventory_items;
drop policy if exists "inventory_admin_insert" on public.inventory_items;
drop policy if exists "inventory_admin_update" on public.inventory_items;
drop policy if exists "inventory_admin_delete" on public.inventory_items;
create policy "inventory_admin_select" on public.inventory_items for select to authenticated using ((select auth.uid())='5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid);
create policy "inventory_admin_insert" on public.inventory_items for insert to authenticated with check ((select auth.uid())='5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid);
create policy "inventory_admin_update" on public.inventory_items for update to authenticated using ((select auth.uid())='5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid) with check ((select auth.uid())='5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid);
create policy "inventory_admin_delete" on public.inventory_items for delete to authenticated using ((select auth.uid())='5c0d47f8-68c1-4a60-a1b8-c80885c385da'::uuid);
