-- White Saffron Stock Sheet Photo Entry setup
-- Run this in Supabase SQL Editor for project tmupbruwmwlrmewhoodn.
-- It creates a private stock photo bucket and stock_entries rows for notebook-style sheets:
-- Qty | Item Name | Date | Name | Sign

create table if not exists public.stock_entries (
  id bigint generated by default as identity primary key,
  sheet_id text,
  sheet_date text,
  row_no integer,
  qty_text text,
  item_name text,
  entry_date text,
  received_by text,
  sign_text text,
  quantity numeric default 0,
  unit text,
  unit_price numeric default 0,
  total_price numeric default 0,
  vendor text,
  photo_path text,
  source_text text,
  status text default 'Needs Review',
  user_id uuid,
  created_by text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.stock_entries add column if not exists sheet_id text;
alter table public.stock_entries add column if not exists sheet_date text;
alter table public.stock_entries add column if not exists row_no integer;
alter table public.stock_entries add column if not exists qty_text text;
alter table public.stock_entries add column if not exists entry_date text;
alter table public.stock_entries add column if not exists received_by text;
alter table public.stock_entries add column if not exists sign_text text;
alter table public.stock_entries add column if not exists item_name text;
alter table public.stock_entries add column if not exists quantity numeric default 0;
alter table public.stock_entries add column if not exists unit text;
alter table public.stock_entries add column if not exists unit_price numeric default 0;
alter table public.stock_entries add column if not exists total_price numeric default 0;
alter table public.stock_entries add column if not exists vendor text;
alter table public.stock_entries add column if not exists photo_path text;
alter table public.stock_entries add column if not exists source_text text;
alter table public.stock_entries add column if not exists status text default 'Needs Review';
alter table public.stock_entries add column if not exists user_id uuid;
alter table public.stock_entries add column if not exists created_by text;
alter table public.stock_entries add column if not exists created_at timestamptz default now();
alter table public.stock_entries add column if not exists updated_at timestamptz default now();

alter table public.stock_entries enable row level security;

drop policy if exists "stock select own or admin" on public.stock_entries;
create policy "stock select own or admin"
on public.stock_entries
for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select auth.jwt() ->> 'email') = 'naappe@gmail.com'
);

drop policy if exists "stock insert own" on public.stock_entries;
create policy "stock insert own"
on public.stock_entries
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "stock update own or admin" on public.stock_entries;
create policy "stock update own or admin"
on public.stock_entries
for update
to authenticated
using (
  user_id = (select auth.uid())
  or (select auth.jwt() ->> 'email') = 'naappe@gmail.com'
)
with check (
  user_id = (select auth.uid())
  or (select auth.jwt() ->> 'email') = 'naappe@gmail.com'
);

drop policy if exists "stock delete admin" on public.stock_entries;
create policy "stock delete admin"
on public.stock_entries
for delete
to authenticated
using ((select auth.jwt() ->> 'email') = 'naappe@gmail.com');

grant select, insert, update, delete on public.stock_entries to authenticated;
grant usage, select on sequence public.stock_entries_id_seq to authenticated;

create index if not exists stock_entries_sheet_id_idx on public.stock_entries(sheet_id);
create index if not exists stock_entries_photo_path_idx on public.stock_entries(photo_path);
create index if not exists stock_entries_created_at_idx on public.stock_entries(created_at desc);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'stock-photos',
  'stock-photos',
  false,
  10485760,
  array['image/jpeg','image/png','image/webp','image/heic','image/heif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "stock photos insert own folder" on storage.objects;
create policy "stock photos insert own folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'stock-photos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "stock photos select own or admin" on storage.objects;
create policy "stock photos select own or admin"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'stock-photos'
  and (
    (storage.foldername(name))[1] = (select auth.uid())::text
    or (select auth.jwt() ->> 'email') = 'naappe@gmail.com'
  )
);

drop policy if exists "stock photos delete admin" on storage.objects;
create policy "stock photos delete admin"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'stock-photos'
  and (select auth.jwt() ->> 'email') = 'naappe@gmail.com'
);
