import {store,money,escapeHtml,text,number,billDate,vendor,status,billNo,itemOf,get} from './store.js';
import {saveBillRecords,updateBill} from './data.js';

const $=s=>document.querySelector(s),content=()=>$('#content');
const today=()=>new Date().toISOString().slice(0,10);
const units=['BTL','ML','L','KG','G','PCS','CTN','DOZ','PKT'];
const methods=['Cash','Bank transfer','Card','Cheque','Credit'];

function canEdit(row){if(store.role==='admin')return true;const t=new Date(get(row,'created_at','updated_at')).getTime();return Number.isFinite(t)&&Date.now()-t<=86400000}
function vendors(){const map=new Map();store.rows.forEach(row=>{const name=vendor(row);if(!name||name==='Unknown supplier')return;if(!map.has(name))map.set(name,{name,tin:'',mobile:'',location:''});const v=map.get(name);v.tin||=text(get(row,'tin','vendor_tin'));v.mobile||=text(get(row,'mobile','phone','vendor_mobile'));v.location||=text(get(row,'location','address'))});return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function itemsOf(row){return Array.isArray(row?.items)&&row.items.length?row.items:[itemOf(row)].filter(Boolean)}
function parsePack(pack,unit,qty=1){const p=text(pack).toLowerCase().replace(/[×*]/g,'x').replace(/\s+/g,''),fallback=text(unit).toUpperCase();let count=1,size=1,kind=fallback;const m=p.match(/^(\d+(?:\.\d+)?)x(\d+(?:\.\d+)?)(kg|g|l|ml|pcs?|btl|pkt)$/),single=p.match(/^(\d+(?:\.\d+)?)(kg|g|l|ml|pcs?|btl|pkt)$/);if(m){count=number(m[1]);size=number(m[2]);kind=m[3].toUpperCase()}else if(single){size=number(single[1]);kind=single[2].toUpperCase()}let base=count*size*number(qty||1);if(kind==='KG')base*=1000;if(kind==='L')base*=1000;return{base,baseUnit:['KG','G'].includes(kind)?'G':['L','ML'].includes(kind)?'ML':'PCS'}}
function calculate(pack,unit,qty,rate){const parsed=parsePack(pack,unit,qty),line=number(qty)*number(rate),small=parsed.base?line/parsed.base:0,large=parsed.baseUnit==='G'||parsed.baseUnit==='ML'?small*1000:small;return{...parsed,line,small,large}}
function rowTemplate(item={}){const qty=number(get(item,'qty','quantity'))||1,rate=number(get(item,'pack_rate','rate'))||(qty?number(get(item,'row_total','total'))/qty:0),unit=text(get(item,'unit')).toUpperCase()||'PCS';return `<div class="bill-row"><label class="item-name">Product<input data-field="description" required value="${escapeHtml(get(item,'description','product','name'))}" placeholder="Product name"></label><label>Pack format<input data-field="pack" value="${escapeHtml(get(item,'pack_format','packing'))}" placeholder="24x330 ml"></label><label>Unit<select data-field="unit">${units.map(value=>`<option ${value===unit?'selected':''}>${value}</option>`).join('')}</select></label><label>Qty<input data-field="qty" type="number" min="0.001" step="any" value="${qty}"></label><label>Pack rate<input data-field="rate" type="number" min="0" step="any" value="${rate||''}" placeholder="MVR"></label><label>GST %<input data-field="gst" type="number" min="0" step="any" value="${number(get(item,'gst'))}"></label><div class="rate-preview"><span data-base>—</span><small data-rates>Enter pack details</small></div><button class="btn danger small remove-row" data-remove type="button">×</button></div>`}

export function newBillPage(){
  const editing=store.editing;
  if(editing&&!canEdit(editing)){store.editing=null;alert('Staff can edit a bill only within 24 hours.');location.hash='#bills';return}
  const existing=editing?itemsOf(editing):[];
  const directory=vendors();
  content().innerHTML=`<form id="billForm" class="bill-form"><section class="card"><header class="card-head"><div><h2>Bill information</h2><small>Vendor and payment details</small></div><button class="btn secondary" type="button" data-route="bills">Close</button></header><div class="card-body form-grid"><label>Vendor<input id="vendor" list="vendorList" required value="${escapeHtml(editing?vendor(editing):'')}" placeholder="Search or type vendor"><datalist id="vendorList">${directory.map(v=>`<option value="${escapeHtml(v.name)}"></option>`).join('')}</datalist></label><label>Bill date<input id="date" type="date" required value="${escapeHtml(editing?billDate(editing):today())}"></label><label>Bill no.<input id="billNo" value="${escapeHtml(editing&&billNo(editing)!=='—'?billNo(editing):'')}" placeholder="Optional"></label><label>Vendor TIN<input id="tin" value="${escapeHtml(editing?text(get(editing,'tin','vendor_tin')):'')}"></label><label>Vendor mobile<input id="mobile" value="${escapeHtml(editing?text(get(editing,'mobile','phone','vendor_mobile')):'')}"></label><label>Location<input id="location" value="${escapeHtml(editing?text(get(editing,'location','address')):'')}"></label><label>Payment status<select id="payment"><option ${!editing||status(editing)==='Pending'?'selected':''}>Pending</option><option ${editing&&status(editing)==='Paid'?'selected':''}>Paid</option></select></label><label>Payment method<select id="method"><option value="">Select method</option>${methods.map(m=>`<option ${editing&&text(get(editing,'payment_method','method'))===m?'selected':''}>${m}</option>`).join('')}</select></label><label>Category<input id="category" value="${escapeHtml(editing?text(get(editing,'category')):'')}" placeholder="Auto or manual"></label></div></section><section class="card"><header class="card-head"><div><h2>Bill items</h2><small>${editing?`${existing.length} saved row${existing.length===1?'':'s'}`:'One row by default; add every item on the supplier bill'}</small></div><button class="btn secondary small" id="addRow" type="button">Add row</button></header><div class="bill-items" id="billItems">${(existing.length?existing:[{}]).map(rowTemplate).join('')}</div></section><section class="card"><div class="card-body bill-footer"><label>Notes<textarea id="notes">${escapeHtml(editing?text(get(editing,'notes')):'')}</textarea></label><div><div class="totals"><div><span>Subtotal</span><strong id="subtotal">MVR 0.00</strong></div><div><span>GST total</span><strong id="gstTotal">MVR 0.00</strong></div><div class="grand"><span>Total due</span><strong id="grandTotal">MVR 0.00</strong></div></div><div class="actions form-actions"><button class="btn" type="submit">Review & save</button><button class="btn secondary" type="button" data-route="bills">Cancel</button></div></div></div></section></form>`;

  document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>location.hash=`#${el.dataset.route}`);
  const vendorMap=new Map(directory.map(v=>[v.name.toLowerCase(),v]));
  $('#vendor').onchange=()=>{const v=vendorMap.get(text($('#vendor').value).toLowerCase());if(!v)return;if(!text($('#tin').value))$('#tin').value=v.tin;if(!text($('#mobile').value))$('#mobile').value=v.mobile;if(!text($('#location').value))$('#location').value=v.location};
  const readItems=()=>[...document.querySelectorAll('.bill-row')].map(row=>{const description=text(row.querySelector('[data-field="description"]').value),pack=text(row.querySelector('[data-field="pack"]').value),unit=row.querySelector('[data-field="unit"]').value,qty=number(row.querySelector('[data-field="qty"]').value),rate=number(row.querySelector('[data-field="rate"]').value),gst=number(row.querySelector('[data-field="gst"]').value);return{row,description,pack,unit,qty,rate,gst,...calculate(pack,unit,qty,rate)}}).filter(i=>i.description||i.rate);
  const totals=()=>{const list=readItems();list.forEach(i=>{i.row.querySelector('[data-base]').textContent=i.base?`${i.base.toLocaleString('en-US')} ${i.baseUnit}`:'—';const small=i.base?`${money(i.small)} / ${i.baseUnit}`:'No base rate',large=i.baseUnit==='G'?`${money(i.large)} / KG`:i.baseUnit==='ML'?`${money(i.large)} / L`:`${money(i.large)} / PCS`;i.row.querySelector('[data-rates]').textContent=`${small} · ${large} · Line ${money(i.line)}`});const sub=list.reduce((sum,i)=>sum+i.line,0),gst=list.reduce((sum,i)=>sum+i.line*i.gst/100,0);$('#subtotal').textContent=money(sub);$('#gstTotal').textContent=money(gst);$('#grandTotal').textContent=money(sub+gst);return{sub,gst,grand:sub+gst,list}};
  const bind=()=>{document.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{if(document.querySelectorAll('.bill-row').length>1)button.closest('.bill-row').remove();totals()});document.querySelectorAll('.bill-row input,.bill-row select').forEach(input=>{input.oninput=totals;input.onchange=totals})};
  $('#addRow').onclick=()=>{$('#billItems').insertAdjacentHTML('beforeend',rowTemplate());bind();totals()};bind();totals();
  $('#billForm').onsubmit=event=>{event.preventDefault();const summary=totals();if(!text($('#vendor').value)||!$('#date').value||!summary.list.length||summary.list.some(i=>!i.description||i.qty<=0)){alert('Vendor, bill date, product and quantity are required.');return}review(summary)};

  function review(summary){const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<section class="modal-card"><header class="card-head"><h2>Review before saving</h2><button class="btn secondary small" data-close>Close</button></header><div class="card-body"><p><strong>${escapeHtml($('#vendor').value)}</strong> · ${escapeHtml($('#date').value)} · ${escapeHtml($('#billNo').value||'No bill number')}</p><div class="table-wrap review-table"><table class="table"><thead><tr><th>Product</th><th>Pack</th><th>Qty</th><th>GST</th><th class="num">Line total</th></tr></thead><tbody>${summary.list.map(i=>`<tr><td><strong>${escapeHtml(i.description)}</strong></td><td>${escapeHtml(i.pack||i.unit)}</td><td>${i.qty}</td><td>${i.gst}%</td><td class="num">${money(i.line+i.line*i.gst/100)}</td></tr>`).join('')}</tbody></table></div><div class="totals review-totals"><div><span>Subtotal</span><strong>${money(summary.sub)}</strong></div><div><span>GST</span><strong>${money(summary.gst)}</strong></div><div class="grand"><span>Total due</span><strong>${money(summary.grand)}</strong></div></div><div class="actions review-actions"><button class="btn secondary" data-close>Back to edit</button><button class="btn" data-confirm>Confirm & save</button></div></div></section>`;document.body.appendChild(modal);modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.remove());modal.querySelector('[data-confirm]').onclick=async()=>{const shared={bill_date:$('#date').value,bill_no:text($('#billNo').value),vendor:text($('#vendor').value),payment_status:$('#payment').value,payment_method:text($('#method').value),notes:text($('#notes').value),tin:text($('#tin').value),mobile:text($('#mobile').value),location:text($('#location').value),category:text($('#category').value)},toItem=i=>({description:i.description,pack_format:i.pack,unit:i.unit,qty:i.qty,pack_rate:i.rate,row_total:i.line,gst:i.gst,base_quantity:i.base,base_unit:i.baseUnit,unit_rate:i.small,large_unit_rate:i.large});const items=summary.list.map(toItem),first=items[0],record={...shared,amount:summary.grand,gst_total:summary.gst,items,...first};try{modal.querySelector('[data-confirm]').disabled=true;if(editing)await updateBill(editing.id,record);else await saveBillRecords([record]);store.editing=null;modal.remove();location.hash='#bills'}catch(error){modal.querySelector('[data-confirm]').disabled=false;alert(error.message)}}}
}