import {store,money,escapeHtml,text,number,billDate,vendor,amount,billNo,itemOf,get} from './store.js';
import {deleteBill} from './data.js';

const $=s=>document.querySelector(s),unique=a=>[...new Set(a.filter(Boolean))];
const dateOnly=d=>new Date(`${d}T00:00:00`),today=()=>new Date().toISOString().slice(0,10),iso=d=>d.toISOString().slice(0,10);
const filterState=store.filters||(store.filters={});
filterState.bills ||= {period:'month',query:'',vendor:'',from:'',to:'',pageSize:20};
let indexCache={revision:-1,rows:[]};

function rangeFor(period,from='',to=''){const now=dateOnly(today()),start=new Date(now),end=new Date(now);if(period==='today')return{from:today(),to:today(),label:'Today'};if(period==='week'){start.setDate(now.getDate()-((now.getDay()+6)%7));return{from:iso(start),to:today(),label:'This Week'}}if(period==='month')return{from:`${today().slice(0,7)}-01`,to:today(),label:'This Month'};if(period==='lastMonth'){start.setDate(1);start.setMonth(start.getMonth()-1);end.setDate(0);return{from:iso(start),to:iso(end),label:'Last Month'}}if(period==='threeMonths'){start.setMonth(start.getMonth()-2);start.setDate(1);return{from:iso(start),to:today(),label:'Last 3 Months'}}if(period==='year')return{from:`${today().slice(0,4)}-01-01`,to:today(),label:'This Year'};if(period==='custom')return{from,to,label:'Custom Range'};return{from:'',to:'',label:'All Time'}}
function inRange(entry,range){return !!entry.date&&(!range.from||entry.date>=range.from)&&(!range.to||entry.date<=range.to)}
function canEdit(row){if(store.role==='admin')return true;const t=new Date(get(row,'created_at','updated_at')).getTime();return Number.isFinite(t)&&Date.now()-t<=86400000}
function formatDateTime(value){const raw=String(value||'');return raw?raw.slice(0,16).replace('T',' '):'Not recorded'}
function recordNumber(row){const id=String(row.id??'').trim();if(/^\d+$/.test(id))return Number(id).toLocaleString('en-US');let hash=0;for(const ch of id)hash=(hash*31+ch.charCodeAt(0))>>>0;return hash?String(hash).padStart(8,'0').slice(-8):'—'}
function itemsOf(row){return Array.isArray(row?.items)&&row.items.length?row.items:[itemOf(row)].filter(Boolean)}
function itemName(item){return text(get(item,'description','product','name'))||'Unnamed item'}
function itemMeta(item){const pack=text(get(item,'pack_format','packing')),unit=text(get(item,'unit')),qty=number(get(item,'qty','quantity'));return[pack,unit,qty?`Qty ${qty}`:''].filter(Boolean).join(' · ')}
function indexedRows(){if(indexCache.revision===store.dataRevision)return indexCache.rows;const rows=store.rows.map(row=>{const items=itemsOf(row),description=text(get(row,'notes','description'))||`${items.length} item${items.length===1?'':'s'}`,numberLabel=recordNumber(row),vendorName=vendor(row),itemSearch=items.flatMap(item=>[itemName(item),itemMeta(item)]).join(' ');return{row,items,description,numberLabel,vendorName,date:billDate(row),search:[numberLabel,billNo(row),description,itemSearch,vendorName].join(' ').toLowerCase()}}).sort((a,b)=>String(get(b.row,'created_at')||b.date).localeCompare(String(get(a.row,'created_at')||a.date)));indexCache={revision:store.dataRevision,rows};return rows}
function itemsMarkup(items){const visible=items.slice(0,3);return `<div class="bill-item-list">${visible.map(item=>`<div class="bill-item-line"><strong>${escapeHtml(itemName(item))}</strong><small class="cell-meta">${escapeHtml(itemMeta(item)||'No pack details')}</small></div>`).join('')}${items.length>3?`<small class="cell-meta">+${items.length-3} more item${items.length-3===1?'':'s'}</small>`:''}</div>`}

export function billsPage(){
  const state=filterState.bills,all=indexedRows();store.pageSize=number(state.pageSize)||20;
  $('#content').innerHTML=`<header class="page-head"><div><h1>Bills</h1><p>Each supplier bill appears once with all saved item rows.</p></div><div class="actions"><button class="btn" data-route="new">+ New Bill</button></div></header><section class="bills-toolbar"><input id="billSearch" placeholder="Search #, bill number, product or vendor" value="${escapeHtml(state.query||'')}"><select id="billPeriod"><option value="today">Today</option><option value="week">This Week</option><option value="month">This Month</option><option value="lastMonth">Last Month</option><option value="threeMonths">Last 3 Months</option><option value="year">This Year</option><option value="custom">Custom Range</option><option value="all">All Time</option></select><select id="billVendor"><option value="">All vendors</option>${unique(all.map(x=>x.vendorName)).sort().map(v=>`<option ${state.vendor===v?'selected':''}>${escapeHtml(v)}</option>`).join('')}</select><label class="bill-custom">From<input id="billFrom" type="date" value="${escapeHtml(state.from||'')}"></label><label class="bill-custom">To<input id="billTo" type="date" value="${escapeHtml(state.to||'')}"></label><select id="billPageSize"><option value="20">20 bills</option><option value="50">50 bills</option></select></section><section class="card"><div class="table-wrap"><table class="table bills-table"><thead><tr><th>#</th><th>Bill Date</th><th>Bill items</th><th>Vendor</th><th class="num">Bill total</th><th>Created</th><th class="action-col">Actions</th></tr></thead><tbody id="billRows"></tbody></table></div><footer class="pager"><span id="pageMeta"></span><div class="actions"><button class="btn secondary small" id="prevPage">Previous</button><button class="btn secondary small" id="nextPage">Next</button></div></footer></section>`;
  $('#billPeriod').value=state.period||'month';$('#billPageSize').value=String(state.pageSize||20);const custom=()=>document.querySelectorAll('.bill-custom').forEach(x=>x.hidden=$('#billPeriod').value!=='custom');custom();
  const draw=()=>{const range=rangeFor(state.period,state.from,state.to),q=String(state.query||'').trim().toLowerCase(),filtered=all.filter(entry=>inRange(entry,range)&&(!q||entry.search.includes(q))&&(!state.vendor||entry.vendorName===state.vendor));const pages=Math.max(1,Math.ceil(filtered.length/store.pageSize));store.page=Math.min(Math.max(1,store.page||1),pages);const start=(store.page-1)*store.pageSize,slice=filtered.slice(start,start+store.pageSize);$('#billRows').innerHTML=slice.map(entry=>{const {row:r,items,numberLabel,vendorName}=entry,edited=formatDateTime(get(r,'updated_at')),created=formatDateTime(get(r,'created_at'));return `<tr><td><strong>${escapeHtml(numberLabel)}</strong><small class="cell-meta">${escapeHtml(billNo(r)==='—'?'No bill number':billNo(r))}</small></td><td><strong>${escapeHtml(entry.date||'No date')}</strong><small class="cell-meta">Last edit: ${escapeHtml(edited)}</small></td><td>${itemsMarkup(items)}</td><td><strong>${escapeHtml(vendorName)}</strong><small class="cell-meta">${items.length} item row${items.length===1?'':'s'}</small></td><td class="num"><strong>${money(amount(r))}</strong></td><td>${escapeHtml(created)}</td><td class="action-col"><div class="actions">${canEdit(r)?`<button class="btn secondary small" data-edit="${r.id}">Edit</button>`:'<span class="locked">Locked</span>'}${store.role==='admin'?`<button class="btn danger small" data-delete="${r.id}">Delete</button>`:''}</div></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No bills match these filters.</td></tr>';$('#pageMeta').textContent=`${filtered.length?start+1:0}–${Math.min(start+store.pageSize,filtered.length)} of ${filtered.length} bills · ${range.label}`;$('#prevPage').disabled=store.page<=1;$('#nextPage').disabled=store.page>=pages;document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>{store.editing=all.find(entry=>String(entry.row.id)===String(x.dataset.edit))?.row;location.hash='#new'});document.querySelectorAll('[data-delete]').forEach(x=>x.onclick=async()=>{if(confirm('Delete this bill and all its items?')){await deleteBill(x.dataset.delete);billsPage()}})};
  const refresh=()=>{store.page=1;draw()};let searchTimer;$('#billSearch').oninput=e=>{state.query=e.target.value;if(state.query.trim()){state.period='all';$('#billPeriod').value='all';custom()}clearTimeout(searchTimer);searchTimer=setTimeout(refresh,120)};$('#billPeriod').onchange=e=>{state.period=e.target.value;custom();refresh()};$('#billVendor').onchange=e=>{state.vendor=e.target.value;refresh()};$('#billFrom').onchange=e=>{state.from=e.target.value;if(state.period==='custom')refresh()};$('#billTo').onchange=e=>{state.to=e.target.value;if(state.period==='custom')refresh()};$('#billPageSize').onchange=e=>{state.pageSize=number(e.target.value);store.pageSize=state.pageSize;refresh()};$('#prevPage').onclick=()=>{store.page--;draw()};$('#nextPage').onclick=()=>{store.page++;draw()};document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>location.hash=`#${el.dataset.route}`);draw();
}
