import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import{normalizeUnit,CANONICAL_UNITS}from'./units.js?v=1.2.0';
const sb=createClient('https://tmupbruwmwlrmewhoodn.supabase.co','sb_publishable_LAn1liS2zqMqlB33IQJxIw_NbgWKix1',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'white-saffron-erp-auth'}});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c])),num=v=>{const n=typeof v==='number'?v:Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0},money=v=>`MVR ${num(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`,date=v=>v?String(v).slice(0,10):'—',today=()=>new Date().toISOString().slice(0,10);
const routes={dashboard:['Dashboard','Operational overview and priority actions.'],products:['Products','Purchasing catalogue, units and reorder settings.'],stock:['Inventory Control','Stock balances, movements and physical adjustments.'],suppliers:['Suppliers','Supplier profiles, contacts and purchasing history.'],bills:['Purchase Invoices','Create, review, approve and manage supplier invoices.'],prices:['Price Analysis','Supplier price history and purchasing trends.'],reports:['Reports','Operational, purchasing and inventory exports.'],approvals:['Approvals & Recovery','Approval queue, deletion requests and recoverable records.'],admin:['Administration','Users, roles and access status.'],settings:['Settings','Company, currency, tax and application defaults.']};
const S={session:null,role:'viewer',route:'dashboard',products:[],suppliers:[],bills:[],billItems:[],movements:[],prices:[],requests:[],trash:[],settings:null,users:[],errors:[],invoiceItems:[]};
const canWrite=()=>['admin','manager','staff'].includes(S.role),canManage=()=>['admin','manager'].includes(S.role),isAdmin=()=>S.role==='admin';
async function pages(table,build,limit=1000){const rows=[];for(let from=0;;from+=limit){const q=build(sb.from(table).select('*')).range(from,from+limit-1),r=await q;if(r.error)throw new Error(`${table}: ${r.error.message}`);rows.push(...(r.data||[]));if(!r.data||r.data.length<limit)break}return rows}
async function load(){S.errors=[];const jobs=[
 pages('supply',q=>q.order('Name'),1000).then(x=>S.products=x).catch(e=>S.errors.push(e.message)),
 pages('vendors',q=>q.is('deleted_at',null).order('name'),1000).then(x=>S.suppliers=x).catch(e=>S.errors.push(e.message)),
 pages('bills',q=>q.is('deleted_at',null).order('bill_day',{ascending:false}),1000).then(x=>S.bills=x).catch(e=>S.errors.push(e.message)),
 pages('bill_items',q=>q.is('deleted_at',null).order('bill_id',{ascending:false}),1000).then(x=>S.billItems=x).catch(e=>S.errors.push(e.message)),
 pages('stock_movements',q=>q.order('created_at',{ascending:false}),1000).then(x=>S.movements=x).catch(e=>S.errors.push(e.message)),
 pages('price_history',q=>q.is('deleted_at',null).order('effective_date',{ascending:false}),1000).then(x=>S.prices=x).catch(e=>S.errors.push(e.message)),
 pages('deletion_requests',q=>q.order('requested_at',{ascending:false}),1000).then(x=>S.requests=x).catch(()=>{}),
 sb.from('company_settings').select('*').maybeSingle().then(r=>{if(!r.error)S.settings=r.data}).catch(()=>{})
 ];
 if(isAdmin())jobs.push(pages('restore_bin',q=>q.is('restored_at',null).order('deleted_at',{ascending:false}),1000).then(x=>S.trash=x).catch(()=>{}),sb.rpc('admin_list_users').then(r=>{if(!r.error)S.users=r.data||[]}).catch(()=>{}));
 await Promise.all(jobs)
}
function setAuth(show){$('#auth').classList.toggle('hidden',!show);$('#erp').classList.toggle('hidden',show)}
function routeTo(r){S.route=routes[r]?r:'dashboard';location.hash=S.route;render();$$('[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===S.route));$('#drawer').classList.remove('open')}
function alertBar(){return S.errors.length?`<div class="alert danger"><strong>Data issue</strong><span>${esc(S.errors.join(' · '))}</span><button class="icon-btn" id="retry">Retry</button></div>`:''}
function pageHead(actions=''){const[h,p]=routes[S.route];return`${alertBar()}<header class="page-head"><div><div class="eyebrow">White Saffron · ${esc(h)}</div><h1>${esc(h)}</h1><p>${esc(p)}</p></div><div class="page-actions">${actions}</div></header>`}
function kpis(items){return`<section class="kpis">${items.map(([l,v,n=''])=>`<article class="kpi"><span>${esc(l)}</span><strong>${v}</strong>${n?`<small>${esc(n)}</small>`:''}</article>`).join('')}</section>`}
function card(title,body,actions=''){return`<section class="panel"><header><h2>${esc(title)}</h2><div>${actions}</div></header>${body}</section>`}
function table(head,body,empty='No records found.'){return`<div class="table-scroll"><table><thead><tr>${head.map(x=>`<th class="${x[1]||''}">${esc(x[0])}</th>`).join('')}</tr></thead><tbody id="dataRows">${body||`<tr><td colspan="${head.length}" class="empty">${esc(empty)}</td></tr>`}</tbody></table></div>`}
function badge(t,kind=''){return`<span class="badge ${kind}">${esc(t)}</span>`}
function productName(id){return S.products.find(x=>String(x.id)===String(id))?.Name||'Unknown product'}
function supplierName(id,fallback=''){return S.suppliers.find(x=>String(x.id)===String(id))?.name||fallback||'Unknown supplier'}
function billAmount(b){return num(b.net_amount??b.amount??b.Amount)}
function billVendor(b){return b.vendor||b.vendor_name||b.Vendor||supplierName(b.vendor_id)}
function billNo(b){return b.bill_no||b.invoice_number||b['Bill No']||`#${b.id}`}
function render(){const fn={dashboard:dashboard,products:products,stock:stock,suppliers:suppliers,bills:bills,prices:prices,reports:reports,approvals:approvals,admin:admin,settings:settings}[S.route];$('#workspace').innerHTML=fn();bindCommon();$('#pageTitle').textContent=routes[S.route][0]}
function bindCommon(){if($('#retry'))$('#retry').onclick=refresh;$$('[data-open-bill]').forEach(b=>b.onclick=()=>openBillDetail(b.dataset.openBill));$$('[data-edit-product]').forEach(b=>b.onclick=()=>openProduct(b.dataset.editProduct));$$('[data-edit-supplier]').forEach(b=>b.onclick=()=>openSupplier(b.dataset.editSupplier))}
async function refresh(){await load();render()}
function dashboard(){const active=S.products.filter(x=>x.is_active!==false),live=active.filter(x=>x.stock_tracking_active),low=live.filter(x=>num(x.stock)<=num(x.minimum_stock)),pending=S.bills.filter(x=>String(x.approval_status||'').toLowerCase()==='draft'),unpaid=S.bills.filter(x=>String(x.payment_status||'').toLowerCase()!=='paid'),month=today().slice(0,7),monthBills=S.bills.filter(x=>date(x.bill_day).startsWith(month)),spend=monthBills.reduce((a,b)=>a+billAmount(b),0),recent=S.bills.slice(0,8);return pageHead(canWrite()?'<button class="btn primary" id="quickBill">New Purchase Invoice</button>':'')+kpis([['This month',money(spend),`${monthBills.length} invoices`],['Products',active.length,`${low.length} need attention`],['Open payments',unpaid.length,'Pending supplier settlement'],['Approvals',pending.length,'Draft invoices']])+`<section class="dashboard-grid">${card('Priority actions',`<div class="priority-list">${low.slice(0,6).map(x=>`<button data-route-link="stock"><span>${esc(x.Name)}</span>${badge(`${num(x.stock)} ${normalizeUnit(x.Unit)}`,'danger')}</button>`).join('')||'<p class="empty compact">No low-stock alerts.</p>'}${pending.slice(0,4).map(x=>`<button data-open-bill="${x.id}"><span>${esc(billNo(x))} · ${esc(billVendor(x))}</span>${badge('Approval required','warn')}</button>`).join('')}</div>`)}${card('Recent purchase invoices',table([['Date'],['Invoice'],['Supplier'],['Amount','num'],['Status']],recent.map(b=>`<tr data-open-bill="${b.id}"><td>${date(b.bill_day)}</td><td><strong>${esc(billNo(b))}</strong></td><td>${esc(billVendor(b))}</td><td class="num">${money(billAmount(b))}</td><td>${badge(b.approval_status||'Recorded',String(b.approval_status).toLowerCase()==='approved'?'good':'warn')}</td></tr>`).join('')))}</section>`}
function products(){const active=S.products.filter(x=>x.is_active!==false),cats=new Set(active.map(x=>x.main_category).filter(Boolean)),live=active.filter(x=>x.stock_tracking_active);return pageHead(canWrite()?'<button class="btn primary" id="newProduct">Add Product</button>':'')+kpis([['Active products',active.length],['Categories',cats.size],['Stock-tracked',live.length],['Inactive',S.products.length-active.length]])+toolbar('Search products','productSearch',true,'productStatus')+card('Product catalogue',table([['Product'],['Category'],['Unit'],['Stock','num'],['Minimum','num'],['Latest rate','num'],['Status'],['']],productRows(S.products)))}
function productRows(rows){return rows.map(x=>`<tr><td><strong>${esc(x.Name||'Unnamed')}</strong><small>${esc(x.subcategory||'')}</small></td><td>${esc(x.main_category||'Uncategorised')}</td><td>${normalizeUnit(x.Unit)}</td><td class="num">${num(x.stock)}</td><td class="num">${num(x.minimum_stock)}</td><td class="num">${money(x.Rate)}</td><td>${badge(x.is_active===false?'Inactive':x.stock_tracking_active?'Tracked':'Not tracked',x.is_active===false?'':x.stock_tracking_active?'good':'warn')}</td><td>${canWrite()?`<button class="link" data-edit-product="${x.id}">Edit</button>`:''}</td></tr>`).join('')}
function stock(){const live=S.products.filter(x=>x.is_active!==false&&x.stock_tracking_active),low=live.filter(x=>num(x.stock)<=num(x.minimum_stock)),total=live.reduce((a,x)=>a+num(x.stock),0),mov=S.movements.slice(0,300);return pageHead(canWrite()?'<button class="btn primary" id="newMovement">Record Movement</button><button class="btn" id="openingCount">Opening Count</button>':'')+kpis([['Tracked products',live.length],['Low stock',low.length],['Total units',total],['Movements',S.movements.length]])+toolbar('Search movement or product','movementSearch',false,'movementType')+card('Inventory movement ledger',table([['Date'],['Product'],['Type'],['Quantity','num'],['Previous','num'],['New balance','num'],['Reference'],['']],movementRows(mov),'No inventory movements have been recorded.'))}
function movementRows(rows){return rows.map(x=>`<tr><td>${date(x.movement_date||x.created_at)}</td><td><strong>${esc(productName(x.supply_id))}</strong></td><td>${badge(String(x.movement_type||'').replaceAll('_',' '),x.is_reversal?'warn':String(x.movement_type).includes('out')?'danger':'good')}</td><td class="num">${num(x.quantity)}</td><td class="num">${num(x.previous_stock)}</td><td class="num">${num(x.new_stock)}</td><td>${esc(x.reference||'—')}</td><td>${canManage()&&!x.is_reversal?`<button class="link" data-reverse="${x.id}">Reverse</button>`:''}</td></tr>`).join('')}
function suppliers(){const active=S.suppliers.filter(x=>x.is_active!==false),used=new Set(S.bills.map(x=>String(x.vendor_id||'')).filter(Boolean));return pageHead(canManage()?'<button class="btn primary" id="newSupplier">Add Supplier</button>':'')+kpis([['Active suppliers',active.length],['Used in invoices',used.size],['With contact',active.filter(x=>x.phone||x.email).length],['Inactive',S.suppliers.length-active.length]])+toolbar('Search suppliers','supplierSearch')+card('Supplier directory',table([['Supplier'],['Phone'],['Email'],['TIN'],['Last purchase'],['Invoices','num'],['']],supplierRows(S.suppliers)))}
function supplierRows(rows){return rows.map(v=>{const vb=S.bills.filter(b=>String(b.vendor_id)===String(v.id)||billVendor(b).toLowerCase()===String(v.name||'').toLowerCase());return`<tr><td><strong>${esc(v.name||'Unnamed')}</strong><small>${esc(v.address||'')}</small></td><td>${esc(v.phone||'—')}</td><td>${esc(v.email||'—')}</td><td>${esc(v.tin||'—')}</td><td>${date(vb[0]?.bill_day)}</td><td class="num">${vb.length}</td><td>${canManage()?`<button class="link" data-edit-supplier="${v.id}">Edit</button>`:''}</td></tr>`}).join('')}
function bills(){const total=S.bills.reduce((a,b)=>a+billAmount(b),0),paid=S.bills.filter(x=>String(x.payment_status).toLowerCase()==='paid'),draft=S.bills.filter(x=>String(x.approval_status).toLowerCase()==='draft');return pageHead(canWrite()?'<button class="btn primary" id="newInvoice">New Purchase Invoice</button>':'')+kpis([['Invoices',S.bills.length],['Total value',money(total)],['Paid',paid.length],['Awaiting approval',draft.length]])+`<section class="filters"><label><span>Search</span><input id="billSearch" type="search" placeholder="Invoice number or supplier"></label><label><span>Approval</span><select id="billApproval"><option value="">All</option><option>draft</option><option>approved</option><option>rejected</option></select></label><label><span>Payment</span><select id="billPayment"><option value="">All</option><option>Pending</option><option>Paid</option></select></label><button class="btn" id="exportBills">Export CSV</button></section>`+card('Purchase invoice register',table([['Date'],['Invoice'],['Supplier'],['Due date'],['Amount','num'],['Payment'],['Approval']],billRows(S.bills)))}
function billRows(rows){return rows.map(b=>`<tr data-open-bill="${b.id}"><td>${date(b.bill_day)}</td><td><strong>${esc(billNo(b))}</strong></td><td>${esc(billVendor(b))}</td><td>${date(b.due_date)}</td><td class="num">${money(billAmount(b))}</td><td>${badge(b.payment_status||'Pending',String(b.payment_status).toLowerCase()==='paid'?'good':'warn')}</td><td>${badge(b.approval_status||'Recorded',String(b.approval_status).toLowerCase()==='approved'?'good':String(b.approval_status).toLowerCase()==='rejected'?'danger':'warn')}</td></tr>`).join('')}
function prices(){const rows=S.prices.slice(0,500),productCount=new Set(rows.map(x=>x.product_id).filter(Boolean)).size;return pageHead('<button class="btn" id="exportPrices">Export CSV</button>')+kpis([['Price records',S.prices.length],['Products covered',productCount],['Structured invoice items',S.billItems.length],['Legacy limitation',Math.max(0,S.bills.length-new Set(S.billItems.map(x=>x.bill_id)).size),'Header-only invoices']])+toolbar('Search product or supplier','priceSearch')+card('Purchase price history',table([['Date'],['Product'],['Supplier'],['Unit'],['Price','num'],['Quantity','num'],['Invoice']],priceRows(rows),'Price history will grow from structured invoices.'))}
function priceRows(rows){return rows.map(x=>`<tr><td>${date(x.effective_date||x.created_at)}</td><td><strong>${esc(productName(S.billItems.find(i=>String(i.id)===String(x.bill_item_id))?.supply_id)||x.product_id||'Product')}</strong></td><td>${esc(supplierName(x.vendor_id))}</td><td>${esc(x.unit_code||'—')}</td><td class="num">${money(x.price)}</td><td class="num">${num(x.quantity)}</td><td><button class="link" data-open-bill="${x.bill_id}">${esc(String(x.bill_id||'—'))}</button></td></tr>`).join('')}
function reports(){const total=S.bills.reduce((a,b)=>a+billAmount(b),0),stockValue=S.products.reduce((a,x)=>a+num(x.stock)*num(x.Rate),0),supplierSpend=new Map;S.bills.forEach(b=>supplierSpend.set(billVendor(b),(supplierSpend.get(billVendor(b))||0)+billAmount(b)));const top=[...supplierSpend.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10);return pageHead('<button class="btn" id="printReport">Print</button><button class="btn primary" id="exportReport">Export Summary</button>')+kpis([['Total purchasing',money(total)],['Inventory value',money(stockValue)],['Suppliers',S.suppliers.length],['Recorded movements',S.movements.length]])+`<section class="report-grid">${card('Available reports',`<div class="report-list"><button data-report="bills"><strong>Purchase invoice register</strong><span>Dates, suppliers, payment and approval</span></button><button data-report="stock"><strong>Inventory valuation</strong><span>Quantity, rate and stock value</span></button><button data-report="low"><strong>Reorder report</strong><span>Low and out-of-stock products</span></button><button data-report="suppliers"><strong>Supplier spend</strong><span>Invoice count and total purchasing</span></button></div>`)}${card('Top supplier spend',table([['Supplier'],['Total','num']],top.map(([n,v])=>`<tr><td>${esc(n)}</td><td class="num">${money(v)}</td></tr>`).join('')))}</section>`}
function approvals(){const pending=S.requests.filter(x=>x.status==='pending'),drafts=S.bills.filter(x=>String(x.approval_status).toLowerCase()==='draft');return pageHead()+kpis([['Draft invoices',drafts.length],['Deletion requests',pending.length],['Recoverable',S.trash.length],['Role',S.role.toUpperCase()]])+`<section class="stack">${card('Invoice approvals',table([['Date'],['Invoice'],['Supplier'],['Amount','num'],['Action']],drafts.map(b=>`<tr><td>${date(b.bill_day)}</td><td><button class="link" data-open-bill="${b.id}">${esc(billNo(b))}</button></td><td>${esc(billVendor(b))}</td><td class="num">${money(billAmount(b))}</td><td>${canManage()?`<button class="link good" data-approve="${b.id}">Approve</button> <button class="link danger" data-reject="${b.id}">Reject</button>`:'Review required'}</td></tr>`).join(''),'No invoices awaiting approval.'))}${card('Deletion requests',table([['Requested'],['Record'],['Reason'],['Status'],['Action']],S.requests.map(x=>`<tr><td>${date(x.requested_at)}</td><td>${esc(x.entity_label||`${x.entity_type} #${x.entity_id}`)}</td><td>${esc(x.reason||'—')}</td><td>${badge(x.status,x.status==='approved'?'good':x.status==='rejected'?'danger':'warn')}</td><td>${isAdmin()&&x.status==='pending'?`<button class="link good" data-review-delete="${x.id}:approved">Approve</button> <button class="link danger" data-review-delete="${x.id}:rejected">Reject</button>`:'—'}</td></tr>`).join(''),'No deletion requests.'))}${isAdmin()?card('Recovery bin',table([['Deleted'],['Record'],['Recovery expires'],['Action']],S.trash.map(x=>`<tr><td>${date(x.deleted_at)}</td><td>${esc(`${x.entity_type} #${x.entity_id}`)}</td><td>${date(new Date(new Date(x.deleted_at).getTime()+30*86400000).toISOString())}</td><td><button class="link" data-restore="${x.id}">Restore</button></td></tr>`).join(''),'Recovery bin is empty.')):''}</section>`}
function admin(){if(!isAdmin())return pageHead()+card('Restricted','<p class="empty">Administrator access is required.</p>');return pageHead()+kpis([['Users',S.users.length],['Active',S.users.filter(x=>x.is_active).length],['Administrators',S.users.filter(x=>x.role==='admin').length],['Signed-in role','ADMIN']])+card('User access',table([['Name'],['Email'],['Role'],['Status'],['Last active'],['Action']],S.users.map(u=>`<tr><td><strong>${esc(u.display_name||'—')}</strong></td><td>${esc(u.email||'—')}</td><td>${badge(u.role||'staff')}</td><td>${badge(u.is_active?'Active':'Disabled',u.is_active?'good':'danger')}</td><td>${date(u.last_active_at||u.last_sign_in_at)}</td><td><button class="link" data-user="${u.user_id}">Manage</button></td></tr>`).join('')))}
function settings(){const x=S.settings||{};return pageHead()+card('Company settings',`<form id="settingsForm" class="form-grid"><label><span>Company name</span><input id="setCompany" value="${esc(x.company_name||'White Saffron')}"></label><label><span>TIN</span><input id="setTin" value="${esc(x.tin||'')}"></label><label><span>Currency</span><input id="setCurrency" value="${esc(x.currency||'MVR')}"></label><label><span>Default GST %</span><input id="setGst" type="number" min="0" step=".01" value="${num(x.default_gst||8)}"></label><label><span>Payment method</span><input id="setPayment" value="${esc(x.default_payment_method||'')}"></label><label class="span-2"><span>Address</span><textarea id="setAddress">${esc(x.address||'')}</textarea></label><label class="span-2"><span>Report footer</span><textarea id="setFooter">${esc(x.report_footer||'')}</textarea></label><div class="span-2 form-actions">${isAdmin()?'<button class="btn primary">Save Settings</button>':'<span class="muted">Administrator access is required to change settings.</span>'}</div></form>`)}
function toolbar(ph,id,units=false,status=''){return`<section class="filters"><label><span>Search</span><input id="${id}" type="search" placeholder="${esc(ph)}"></label>${units?`<label><span>Unit</span><select id="unitFilter"><option value="">All units</option>${CANONICAL_UNITS.map(x=>`<option>${x}</option>`).join('')}</select></label>`:''}${status?`<label><span>Status</span><select id="${status}"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label>`:''}</section>`}
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function message(text,kind='good'){const t=document.createElement('div');t.className=`toast ${kind}`;t.textContent=text;$('#toasts').append(t);setTimeout(()=>t.remove(),4200)}
function openProduct(id=''){const x=S.products.find(z=>String(z.id)===String(id))||{};modal(id?'Edit Product':'Add Product',`<form id="productForm" class="form-grid"><label class="span-2"><span>Product name</span><input id="pName" required value="${esc(x.Name||'')}"></label><label><span>Unit</span><select id="pUnit">${CANONICAL_UNITS.map(u=>`<option ${normalizeUnit(x.Unit)===u?'selected':''}>${u}</option>`).join('')}</select></label><label><span>Category</span><input id="pCategory" value="${esc(x.main_category||'')}"></label><label><span>Subcategory</span><input id="pSubcategory" value="${esc(x.subcategory||'')}"></label><label><span>Minimum stock</span><input id="pMinimum" type="number" min="0" step=".0001" value="${num(x.minimum_stock)}"></label><label class="check"><input id="pActive" type="checkbox" ${x.is_active===false?'':'checked'}><span>Active product</span></label><div class="span-2 form-actions"><button type="button" class="btn" data-close>Cancel</button><button class="btn primary">Save Product</button></div></form>`);$('#productForm').onsubmit=async e=>{e.preventDefault();const data={Name:$('#pName').value.trim(),Unit:normalizeUnit($('#pUnit').value),main_category:$('#pCategory').value.trim()||null,subcategory:$('#pSubcategory').value.trim()||null,minimum_stock:num($('#pMinimum').value),is_active:$('#pActive').checked,updated_at:new Date().toISOString()};const r=id?await sb.from('supply').update(data).eq('id',id):await sb.from('supply').insert({...data,stock:0,stock_tracking_active:false}).select().single();await finish(r,'Product saved')};bindModalClose()}
function openSupplier(id=''){const x=S.suppliers.find(z=>String(z.id)===String(id))||{};modal(id?'Edit Supplier':'Add Supplier',`<form id="supplierForm" class="form-grid"><label class="span-2"><span>Supplier name</span><input id="vName" required value="${esc(x.name||'')}"></label><label><span>Phone</span><input id="vPhone" value="${esc(x.phone||'')}"></label><label><span>Email</span><input id="vEmail" type="email" value="${esc(x.email||'')}"></label><label><span>TIN</span><input id="vTin" value="${esc(x.tin||'')}"></label><label><span>Default payment</span><input id="vPayment" value="${esc(x.default_payment_method||'')}"></label><label class="span-2"><span>Address</span><textarea id="vAddress">${esc(x.address||'')}</textarea></label><label class="span-2"><span>Bank details</span><textarea id="vBank">${esc(x.bank_details||'')}</textarea></label><label class="span-2"><span>Notes</span><textarea id="vNotes">${esc(x.notes||'')}</textarea></label><label class="check"><input id="vActive" type="checkbox" ${x.is_active===false?'':'checked'}><span>Active supplier</span></label><div class="span-2 form-actions"><button type="button" class="btn" data-close>Cancel</button><button class="btn primary">Save Supplier</button></div></form>`);$('#supplierForm').onsubmit=async e=>{e.preventDefault();const data={name:$('#vName').value.trim(),phone:$('#vPhone').value.trim()||null,email:$('#vEmail').value.trim()||null,tin:$('#vTin').value.trim()||null,default_payment_method:$('#vPayment').value.trim()||null,address:$('#vAddress').value.trim()||null,bank_details:$('#vBank').value.trim()||null,notes:$('#vNotes').value.trim()||null,is_active:$('#vActive').checked,updated_at:new Date().toISOString()};const r=id?await sb.from('vendors').update(data).eq('id',id):await sb.from('vendors').insert(data).select().single();await finish(r,'Supplier saved')};bindModalClose()}
function invoiceForm(b=null){S.invoiceItems=b?invoiceItemsFor(b):[{description:'',supply_id:'',quantity:1,unit:'PCS',unit_rate:0,gst_rate:num(S.settings?.default_gst||8)}];modal(b?'Edit Purchase Invoice':'New Purchase Invoice',`<form id="invoiceForm"><div class="form-grid"><label><span>Invoice date</span><input id="iDate" type="date" required value="${date(b?.bill_day)!=='—'?date(b?.bill_day):today()}"></label><label><span>Supplier</span><select id="iSupplier" required><option value="">Select supplier</option>${S.suppliers.filter(x=>x.is_active!==false).map(v=>`<option value="${v.id}" ${String(b?.vendor_id)===String(v.id)?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label><span>Invoice number</span><input id="iNumber" required value="${esc(b?billNo(b):'')}"></label><label><span>Due date</span><input id="iDue" type="date" value="${b?.due_date||''}"></label><label><span>Payment method</span><select id="iPayment"><option value="">Not specified</option>${['Cash','Card','Transfer','Credit','Other'].map(x=>`<option ${String(b?.payment_method).toLowerCase()===x.toLowerCase()?'selected':''}>${x}</option>`).join('')}</select></label><label><span>Payment status</span><select id="iPaymentStatus"><option ${b?.payment_status!=='Paid'?'selected':''}>Pending</option><option ${b?.payment_status==='Paid'?'selected':''}>Paid</option></select></label><label class="span-2"><span>Notes</span><textarea id="iNotes">${esc(b?.notes||'')}</textarea></label></div><div class="section-line"><h3>Invoice items</h3><button type="button" class="btn" id="addLine">Add Item</button></div><div id="invoiceLines"></div><div class="invoice-total"><span>Subtotal <strong id="invSub">MVR 0.00</strong></span><span>GST <strong id="invGst">MVR 0.00</strong></span><span>Net total <strong id="invNet">MVR 0.00</strong></span></div><div id="formError" class="alert danger hidden"></div><div class="form-actions"><button type="button" class="btn" data-close>Cancel</button><button class="btn primary" id="saveInvoice">${b?'Update':'Save'} Invoice</button></div></form>`);drawInvoiceLines();$('#addLine').onclick=()=>{S.invoiceItems.push({description:'',supply_id:'',quantity:1,unit:'PCS',unit_rate:0,gst_rate:num(S.settings?.default_gst||8)});drawInvoiceLines()};$('#invoiceForm').onsubmit=e=>saveInvoice(e,b);bindModalClose()}
function invoiceItemsFor(b){const rows=S.billItems.filter(x=>String(x.bill_id)===String(b.id));if(rows.length)return rows.map(x=>({description:x.description||x.item_name,supply_id:x.supply_id||'',quantity:num(x.quantity),unit:normalizeUnit(x.unit),unit_rate:num(x.unit_rate),gst_rate:num(x.gst_rate),pack_format:x.pack_format||''}));return Array.isArray(b.items)?b.items.map(x=>({description:x.description||x.name||'',supply_id:x.supply_id||'',quantity:num(x.quantity??x.qty),unit:normalizeUnit(x.unit),unit_rate:num(x.unit_rate??x.rate),gst_rate:num(x.gst_rate??x.gst),pack_format:x.pack_format||''})):[]}
function drawInvoiceLines(){$('#invoiceLines').innerHTML=S.invoiceItems.map((x,i)=>`<div class="invoice-line"><label><span>Product</span><select data-line="${i}" data-field="supply_id" required><option value="">Select product</option>${S.products.filter(p=>p.is_active!==false).map(p=>`<option value="${p.id}" ${String(p.id)===String(x.supply_id)?'selected':''}>${esc(p.Name)}</option>`).join('')}</select></label><label><span>Quantity</span><input data-line="${i}" data-field="quantity" type="number" min=".0001" step=".0001" value="${x.quantity}"></label><label><span>Unit</span><select data-line="${i}" data-field="unit">${CANONICAL_UNITS.map(u=>`<option ${u===normalizeUnit(x.unit)?'selected':''}>${u}</option>`).join('')}</select></label><label><span>Unit rate</span><input data-line="${i}" data-field="unit_rate" type="number" min="0" step=".01" value="${x.unit_rate}"></label><label><span>GST %</span><input data-line="${i}" data-field="gst_rate" type="number" min="0" max="100" step=".01" value="${x.gst_rate}"></label><button type="button" class="icon-btn danger" data-remove-line="${i}" ${S.invoiceItems.length===1?'disabled':''}>Remove</button></div>`).join('');$$('[data-field]').forEach(el=>el.oninput=el.onchange=()=>{const i=+el.dataset.line,f=el.dataset.field;S.invoiceItems[i][f]=el.value;if(f==='supply_id'){const p=S.products.find(x=>String(x.id)===String(el.value));if(p){S.invoiceItems[i].description=p.Name;S.invoiceItems[i].unit=normalizeUnit(p.Unit);S.invoiceItems[i].unit_rate=num(p.Rate);drawInvoiceLines();return}}invoiceTotals()});$$('[data-remove-line]').forEach(b=>b.onclick=()=>{S.invoiceItems.splice(+b.dataset.removeLine,1);drawInvoiceLines()});invoiceTotals()}
function invoiceTotals(){let sub=0,gst=0;S.invoiceItems.forEach(x=>{const s=num(x.quantity)*num(x.unit_rate);sub+=s;gst+=s*num(x.gst_rate)/100});$('#invSub').textContent=money(sub);$('#invGst').textContent=money(gst);$('#invNet').textContent=money(sub+gst)}
async function saveInvoice(e,b){e.preventDefault();const supplier=S.suppliers.find(x=>String(x.id)===String($('#iSupplier').value)),items=S.invoiceItems.map((x,i)=>({...x,quantity:num(x.quantity),unit_rate:num(x.unit_rate),gst_rate:num(x.gst_rate),sort_order:i+1}));if(!supplier||items.some(x=>!x.supply_id||x.quantity<=0)){formError('Complete every invoice item.');return}const data={bill_day:$('#iDate').value,vendor_id:supplier.id,vendor:supplier.name,bill_no:$('#iNumber').value.trim(),due_date:$('#iDue').value,payment_method:$('#iPayment').value,payment_status:$('#iPaymentStatus').value,notes:$('#iNotes').value.trim(),currency:S.settings?.currency||'MVR',approval_status:S.role==='staff'?'draft':'approved'};$('#saveInvoice').disabled=true;const r=b?await sb.rpc('update_bill_transaction',{p_bill_id:b.id,p_bill:data,p_items:items}):await sb.rpc('create_bill_transaction',{p_bill:data,p_items:items});$('#saveInvoice').disabled=false;if(r.error){formError(r.error.message);return}closeModal();message(b?'Invoice updated':'Invoice created');await refresh()}
function formError(t){$('#formError').textContent=t;$('#formError').classList.remove('hidden')}
function openBillDetail(id){const b=S.bills.find(x=>String(x.id)===String(id));if(!b)return;const items=invoiceItemsFor(b);modal(`Invoice ${billNo(b)}`,`<div class="detail-grid"><div><span>Supplier</span><strong>${esc(billVendor(b))}</strong></div><div><span>Invoice date</span><strong>${date(b.bill_day)}</strong></div><div><span>Due date</span><strong>${date(b.due_date)}</strong></div><div><span>Payment</span><strong>${esc(b.payment_status||'Pending')}</strong></div><div><span>Approval</span><strong>${esc(b.approval_status||'Recorded')}</strong></div><div><span>Net total</span><strong>${money(billAmount(b))}</strong></div></div>${table([['Product'],['Qty','num'],['Unit'],['Rate','num'],['GST','num'],['Total','num']],items.map(x=>`<tr><td>${esc(x.description)}</td><td class="num">${num(x.quantity)}</td><td>${normalizeUnit(x.unit)}</td><td class="num">${money(x.unit_rate)}</td><td class="num">${num(x.gst_rate)}%</td><td class="num">${money(num(x.quantity)*num(x.unit_rate)*(1+num(x.gst_rate)/100))}</td></tr>`).join(''),'No recoverable line-item detail exists for this legacy invoice.')}<div class="form-actions">${isAdmin()?`<button class="btn" id="editInvoice">Edit</button><button class="btn danger" id="trashInvoice">Move to Trash</button>`:canWrite()?'<button class="btn danger" id="requestDelete">Request Deletion</button>':''}<button class="btn" id="printInvoice">Print</button><button class="btn" data-close>Close</button></div>`);if($('#editInvoice'))$('#editInvoice').onclick=()=>invoiceForm(b);if($('#trashInvoice'))$('#trashInvoice').onclick=()=>trashBill(b);if($('#requestDelete'))$('#requestDelete').onclick=()=>requestDelete(b);if($('#printInvoice'))$('#printInvoice').onclick=()=>window.print();bindModalClose()}
async function trashBill(b){if(!confirm(`Move invoice ${billNo(b)} to the 30-day recovery bin?`))return;await finish(await sb.rpc('trash_bill',{p_bill_id:b.id}),'Invoice moved to recovery bin')}
async function requestDelete(b){const reason=prompt('Reason for deletion request:');if(!reason)return;await finish(await sb.from('deletion_requests').insert({entity_type:'bill',entity_id:String(b.id),entity_label:`Invoice ${billNo(b)}`,requested_by:S.session.user.id,reason,status:'pending'}),'Deletion request submitted')}
function movementForm(){modal('Record Inventory Movement',`<form id="movementForm" class="form-grid"><label class="span-2"><span>Product</span><select id="mProduct" required><option value="">Select product</option>${S.products.filter(x=>x.is_active!==false&&x.stock_tracking_active).map(x=>`<option value="${x.id}">${esc(x.Name)} · ${num(x.stock)} ${normalizeUnit(x.Unit)}</option>`).join('')}</select></label><label><span>Movement type</span><select id="mType"><option value="purchase">Receipt</option><option value="usage">Usage</option><option value="return_in">Return in</option><option value="return_out">Return out</option>${isAdmin()?'<option value="adjustment_in">Adjustment in</option><option value="adjustment_out">Adjustment out</option>':''}</select></label><label><span>Date</span><input id="mDate" type="date" value="${today()}"></label><label><span>Quantity</span><input id="mQty" type="number" min=".0001" step=".0001" required></label><label><span>Rate (optional)</span><input id="mRate" type="number" min="0" step=".01"></label><label class="span-2"><span>Reference</span><input id="mReference"></label><label class="span-2"><span>Reason</span><textarea id="mReason" required></textarea></label><div class="span-2 form-actions"><button type="button" class="btn" data-close>Cancel</button><button class="btn primary">Record Movement</button></div></form>`);$('#movementForm').onsubmit=async e=>{e.preventDefault();const r=await sb.rpc('record_stock_movement',{p_supply_id:+$('#mProduct').value,p_movement_type:$('#mType').value,p_quantity:num($('#mQty').value),p_reference:$('#mReference').value.trim(),p_reason:$('#mReason').value.trim(),p_movement_date:$('#mDate').value,p_rate:$('#mRate').value?num($('#mRate').value):null});await finish(r,'Inventory movement recorded')};bindModalClose()}
async function finish(r,ok){if(r.error){message(r.error.message,'danger');return false}closeModal();message(ok);await refresh();return true}
function bindModalClose(){$$('[data-close]').forEach(x=>x.onclick=closeModal)}
function csv(name,rows){const data=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function bindRoute(){if($('#quickBill'))$('#quickBill').onclick=()=>invoiceForm();if($('#newProduct'))$('#newProduct').onclick=()=>openProduct();if($('#newSupplier'))$('#newSupplier').onclick=()=>openSupplier();if($('#newInvoice'))$('#newInvoice').onclick=()=>invoiceForm();if($('#newMovement'))$('#newMovement').onclick=movementForm;if($('#openingCount'))$('#openingCount').onclick=openOpeningCount;$$('[data-route-link]').forEach(x=>x.onclick=()=>routeTo(x.dataset.routeLink));
 if($('#productSearch')){const f=()=>{const q=$('#productSearch').value.toLowerCase(),u=$('#unitFilter').value,s=$('#productStatus').value;$('#dataRows').innerHTML=productRows(S.products.filter(x=>(!q||`${x.Name} ${x.main_category}`.toLowerCase().includes(q))&&(!u||normalizeUnit(x.Unit)===u)&&(!s||(s==='active')===(x.is_active!==false))));bindCommon()};$('#productSearch').oninput=f;$('#unitFilter').onchange=f;$('#productStatus').onchange=f}
 if($('#supplierSearch'))$('#supplierSearch').oninput=()=>{$('#dataRows').innerHTML=supplierRows(S.suppliers.filter(x=>`${x.name} ${x.phone} ${x.email} ${x.tin}`.toLowerCase().includes($('#supplierSearch').value.toLowerCase())));bindCommon()};
 if($('#billSearch')){const f=()=>{const q=$('#billSearch').value.toLowerCase(),a=$('#billApproval').value,p=$('#billPayment').value;$('#dataRows').innerHTML=billRows(S.bills.filter(x=>(!q||`${billNo(x)} ${billVendor(x)}`.toLowerCase().includes(q))&&(!a||x.approval_status===a)&&(!p||x.payment_status===p)));bindCommon()};$('#billSearch').oninput=f;$('#billApproval').onchange=f;$('#billPayment').onchange=f}
 if($('#movementSearch')){$('#movementSearch').oninput=()=>{$('#dataRows').innerHTML=movementRows(S.movements.filter(x=>`${productName(x.supply_id)} ${x.reference} ${x.movement_type}`.toLowerCase().includes($('#movementSearch').value.toLowerCase())));bindActions()}}
 if($('#exportBills'))$('#exportBills').onclick=()=>csv('purchase-invoices.csv',[['Date','Invoice','Supplier','Amount','Payment','Approval'],...S.bills.map(b=>[date(b.bill_day),billNo(b),billVendor(b),billAmount(b),b.payment_status,b.approval_status])]);
 if($('#exportPrices'))$('#exportPrices').onclick=()=>csv('price-history.csv',[['Date','Product ID','Supplier','Unit','Price','Quantity','Invoice'],...S.prices.map(x=>[date(x.effective_date),x.product_id,supplierName(x.vendor_id),x.unit_code,x.price,x.quantity,x.bill_id])]);
 if($('#exportReport'))$('#exportReport').onclick=()=>csv('procurement-summary.csv',[['Metric','Value'],['Invoices',S.bills.length],['Purchasing total',S.bills.reduce((a,b)=>a+billAmount(b),0)],['Products',S.products.length],['Suppliers',S.suppliers.length],['Movements',S.movements.length]]);if($('#printReport'))$('#printReport').onclick=()=>window.print();$$('[data-report]').forEach(x=>x.onclick=()=>exportNamed(x.dataset.report));
 bindActions();bindCommon()}
function bindActions(){$$('[data-reverse]').forEach(x=>x.onclick=async()=>{const reason=prompt('Reason for reversal:');if(reason)await finish(await sb.rpc('reverse_stock_movement',{p_movement_id:+x.dataset.reverse,p_reason:reason}),'Movement reversed')});$$('[data-approve]').forEach(x=>x.onclick=()=>setApproval(x.dataset.approve,'approved'));$$('[data-reject]').forEach(x=>x.onclick=()=>setApproval(x.dataset.reject,'rejected'));$$('[data-review-delete]').forEach(x=>x.onclick=async()=>{const[id,decision]=x.dataset.reviewDelete.split(':');await finish(await sb.rpc('review_bill_deletion_request',{p_request_id:+id,p_decision:decision}),`Deletion request ${decision}`)});$$('[data-restore]').forEach(x=>x.onclick=async()=>await finish(await sb.rpc('restore_bill_from_trash',{p_restore_id:+x.dataset.restore}),'Invoice restored'));$$('[data-user]').forEach(x=>x.onclick=()=>openUser(x.dataset.user))}
async function setApproval(id,status){await finish(await sb.from('bills').update({approval_status:status,approved_at:status==='approved'?new Date().toISOString():null,approved_by:status==='approved'?S.session.user.id:null}).eq('id',id),`Invoice ${status}`)}
function openUser(id){const u=S.users.find(x=>x.user_id===id);modal('Manage User',`<form id="userForm" class="form-grid"><label class="span-2"><span>Email</span><input disabled value="${esc(u.email)}"></label><label><span>Display name</span><input id="uName" value="${esc(u.display_name||'')}"></label><label><span>Role</span><select id="uRole">${['admin','manager','staff','viewer'].map(x=>`<option ${u.role===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="check"><input id="uActive" type="checkbox" ${u.is_active?'checked':''}><span>Active account</span></label><div class="span-2 form-actions"><button type="button" class="btn" data-close>Cancel</button><button class="btn primary">Save User</button></div></form>`);$('#userForm').onsubmit=async e=>{e.preventDefault();await finish(await sb.rpc('admin_update_user',{p_user_id:id,p_role:$('#uRole').value,p_is_active:$('#uActive').checked,p_display_name:$('#uName').value.trim()}),'User access updated')};bindModalClose()}
function openOpeningCount(){modal('Opening Stock Count',`<form id="countForm"><p class="muted">Enter physical quantities. Saving activates tracking for all selected products.</p><div class="count-list">${S.products.filter(x=>x.is_active!==false).map(x=>`<div class="count-row" data-count-id="${x.id}"><strong>${esc(x.Name)}</strong><span>${normalizeUnit(x.Unit)}</span><input data-count-stock type="number" min="0" step=".0001" value="${num(x.stock)}"><input data-count-min type="number" min="0" step=".0001" value="${num(x.minimum_stock)}"><input data-count-active type="checkbox" checked></div>`).join('')}</div><div class="form-actions"><button type="button" class="btn" data-close>Cancel</button><button class="btn primary">Activate Stock</button></div></form>`);$('#countForm').onsubmit=async e=>{e.preventDefault();const p=$$('[data-count-id]').map(r=>({id:+r.dataset.countId,stock:num(r.querySelector('[data-count-stock]').value),minimum_stock:num(r.querySelector('[data-count-min]').value),active:r.querySelector('[data-count-active]').checked}));await finish(await sb.rpc('start_stock_count',{p_counts:p}),'Opening stock saved')};bindModalClose()}
function exportNamed(kind){if(kind==='stock')csv('inventory-valuation.csv',[['Product','Unit','Stock','Rate','Value'],...S.products.map(x=>[x.Name,normalizeUnit(x.Unit),x.stock,x.Rate,num(x.stock)*num(x.Rate)])]);if(kind==='low')csv('reorder-report.csv',[['Product','Unit','Stock','Minimum'],...S.products.filter(x=>x.stock_tracking_active&&num(x.stock)<=num(x.minimum_stock)).map(x=>[x.Name,normalizeUnit(x.Unit),x.stock,x.minimum_stock])]);if(kind==='bills')$('#exportBills')?.click();if(kind==='suppliers'){const m=new Map;S.bills.forEach(b=>{const n=billVendor(b),z=m.get(n)||[0,0];m.set(n,[z[0]+1,z[1]+billAmount(b)])});csv('supplier-spend.csv',[['Supplier','Invoices','Total'],...[...m].map(([n,z])=>[n,...z])])}}
async function saveSettings(e){e.preventDefault();if(!isAdmin())return;const data={company_name:$('#setCompany').value.trim(),tin:$('#setTin').value.trim(),currency:$('#setCurrency').value.trim(),default_gst:num($('#setGst').value),default_payment_method:$('#setPayment').value.trim(),address:$('#setAddress').value.trim(),report_footer:$('#setFooter').value.trim(),updated_at:new Date().toISOString(),updated_by:S.session.user.id};await finish(await sb.from('company_settings').update(data).eq('id',S.settings.id),'Settings saved')}
const originalRender=render;render=function(){originalRender();bindRoute();if($('#settingsForm'))$('#settingsForm').onsubmit=saveSettings};
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').classList.add('hidden');$('#loginButton').disabled=true;const{data,error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});$('#loginButton').disabled=false;if(error){$('#loginError').textContent=error.message;$('#loginError').classList.remove('hidden');return}await start(data.session)};
async function start(session){S.session=session;setAuth(false);const r=await sb.from('user_roles').select('*').eq('user_id',session.user.id).eq('is_active',true).maybeSingle();S.role=String(r.data?.role||'viewer').toLowerCase();$('#accountName').textContent=r.data?.display_name||session.user.email;$('#accountRole').textContent=S.role;await load();routeTo((location.hash||'#dashboard').slice(1))}
$('#logout').onclick=async()=>{await sb.auth.signOut();setAuth(true)};$$('[data-route]').forEach(x=>x.onclick=()=>routeTo(x.dataset.route));$('#menuButton').onclick=()=>$('#drawer').classList.toggle('open');$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};window.addEventListener('hashchange',()=>routeTo(location.hash.slice(1)));const{data:{session}}=await sb.auth.getSession();session?await start(session):setAuth(true);
