import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import{normalizeUnit,CANONICAL_UNITS}from'./units.js?v=1.2.0';
const sb=createClient('https://tmupbruwmwlrmewhoodn.supabase.co','sb_publishable_LAn1liS2zqMqlB33IQJxIw_NbgWKix1',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'white-saffron-erp-auth'}});
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c])),num=v=>{const n=typeof v==='number'?v:Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0},money=v=>`MVR ${num(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const state={session:null,role:'viewer',route:'inventory',supply:[],vendors:[],bills:[],prices:[],items:[],errors:[]};
const routes=['inventory','vendors','stock','bills','prices'];
const titles={inventory:['01 Inventory','Inventory','Products, units, stock levels and latest purchasing information.'],vendors:['02 Vendors','Vendors','Supplier contacts and purchasing activity.'],stock:['03 Stock','Stock','Live quantities, minimum levels and replenishment status.'],bills:['04 Bills','Purchase Bills','Search purchases and record new operational bills.'],prices:['05 Prices','Price Intelligence','Latest and previous supplier prices by product.']};
function setAuth(show){$('#auth').classList.toggle('hidden',!show);$('#app').classList.toggle('hidden',show)}
function canWrite(){return['admin','manager','staff'].includes(state.role)}
function nav(){document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));$('#pageName').textContent=titles[state.route][1]}
function go(route){state.route=routes.includes(route)?route:'inventory';location.hash=state.route;nav();render()}
async function safe(table,query){try{const r=await query;if(r.error){state.errors.push(`${table}: ${r.error.message}`);return[]}return r.data||[]}catch(e){state.errors.push(`${table}: ${e.message||e}`);return[]}}
async function allBills(){const rows=[];for(let from=0;;from+=1000){const page=await sb.from('bills').select('*').is('deleted_at',null).order('bill_day',{ascending:false}).range(from,from+999);if(page.error){state.errors.push(`bills: ${page.error.message}`);break}rows.push(...(page.data||[]));if(!page.data||page.data.length<1000)break}return rows}
async function load(){const [supply,vendors,bills,prices]=await Promise.all([
 safe('supply',sb.from('supply').select('*').eq('is_active',true).order('Name').limit(1000)),
 safe('vendors',sb.from('vendors').select('*').is('deleted_at',null).order('name').limit(500)),
 allBills(),
 safe('prices',sb.from('supply_purchase_summary').select('*').limit(1000))
]);state.supply=supply;state.vendors=vendors;state.bills=bills;state.prices=prices}
function hero(actions=''){const[t,h,p]=titles[state.route];return`${state.errors.length?`<div class="error data-error" role="alert"><strong>Some data could not load.</strong> ${esc(state.errors.join(' | '))} <button class="btn" id="retryLoad" type="button">Retry</button></div>`:''}<header class="hero"><div><div class="kicker">${t}</div><h1>${h}</h1><p>${p}</p></div><div class="actions">${actions}</div></header>`}
function stats(values){return`<section class="stats">${values.map(x=>`<article class="card stat"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('')}</section>`}
function table(head,body,empty='No records found.'){return`<section class="card table-wrap"><table><thead><tr>${head.map(x=>`<th class="${x[1]||''}">${x[0]}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${head.length}" class="empty">${empty}</td></tr>`}</tbody></table></section>`}
function render(){nav();if(state.route==='inventory')renderInventory();if(state.route==='vendors')renderVendors();if(state.route==='stock')renderStock();if(state.route==='bills')renderBills();if(state.route==='prices')renderPrices();if($('#retryLoad'))$('#retryLoad').onclick=async()=>{state.errors=[];await load();render()}}
function renderInventory(){const live=state.supply.filter(x=>x.stock_tracking_active),low=live.filter(x=>num(x.stock??x.current_stock)<=num(x.minimum_stock)),cats=new Set(state.supply.map(x=>x.main_category||x.category).filter(Boolean));$('#content').innerHTML=hero()+stats([['Active items',state.supply.length],['Live stock',live.length],['Low stock',low.length],['Categories',cats.size]])+filters('Search item','inventorySearch',true,true)+table([['Item'],['Category'],['Unit'],['Stock','num'],['Minimum','num'],['Latest vendor'],['Latest price','num'],['Status']],inventoryRows(state.supply));bindFilters('inventory',drawInventory)}
function inventoryRows(rows){return rows.map(x=>{const stock=num(x.stock??x.current_stock),min=num(x.minimum_stock),live=x.stock_tracking_active,stateText=!live?'Not live':stock<=0?'Out':stock<=min?'Low':'Healthy',cls=!live?'':stock<=0?'bad':stock<=min?'warn':'good';return`<tr><td><strong>${esc(x.Name||x.name||x.item_name||'Unnamed')}</strong></td><td>${esc(x.main_category||x.category||'—')}</td><td>${normalizeUnit(x.Unit||x.unit)}</td><td class="num">${stock}</td><td class="num">${min}</td><td>${esc(x.latest_vendor||x.vendor||'—')}</td><td class="num">${money(x.latest_price||x.Rate||x.rate)}</td><td><span class="badge ${cls}">${stateText}</span></td></tr>`}).join('')}
function drawInventory(){const q=$('#inventorySearch').value.toLowerCase(),u=$('#unitFilter').value,s=$('#statusFilter').value;const rows=state.supply.filter(x=>{const name=`${x.Name||x.name||''} ${x.main_category||x.category||''}`.toLowerCase(),unit=normalizeUnit(x.Unit||x.unit),stock=num(x.stock??x.current_stock),min=num(x.minimum_stock),status=!x.stock_tracking_active?'inactive':stock<=min?'low':'healthy';return(!q||name.includes(q))&&(!u||u===unit)&&(!s||s===status)});$('#dataRows').innerHTML=inventoryRows(rows)||`<tr><td colspan="8" class="empty">No items found.</td></tr>`}
function renderStock(){const live=state.supply.filter(x=>x.stock_tracking_active),low=live.filter(x=>num(x.stock??x.current_stock)<=num(x.minimum_stock)),out=live.filter(x=>num(x.stock??x.current_stock)<=0),total=live.reduce((a,x)=>a+num(x.stock??x.current_stock),0);$('#content').innerHTML=hero(canWrite()?'<button class="btn primary" id="startStockCount">Start Stock Count</button>':'')+stats([['Live items',live.length],['Low stock',low.length],['Out of stock',out.length],['Total quantity',total]])+filters('Search live stock','stockSearch',true,false)+table([['Item'],['Category'],['Unit'],['Current stock','num'],['Minimum','num'],['Status'],['Updated']],stockRows(live));bindFilters('stock',drawStock);if($('#startStockCount'))$('#startStockCount').onclick=openStockCount}
function stockRows(rows){return rows.map(x=>{const st=num(x.stock??x.current_stock),min=num(x.minimum_stock),label=st<=0?'Out':st<=min?'Low':'Healthy',cls=st<=0?'bad':st<=min?'warn':'good';return`<tr><td><strong>${esc(x.Name||x.name||'Unnamed')}</strong></td><td>${esc(x.main_category||x.category||'—')}</td><td>${normalizeUnit(x.Unit||x.unit)}</td><td class="num">${st}</td><td class="num">${min}</td><td><span class="badge ${cls}">${label}</span></td><td>${esc(String(x.stock_updated_at||x.updated_at||x.stock_initialized_at||'—').slice(0,10))}</td></tr>`}).join('')}
function drawStock(){const q=$('#stockSearch').value.toLowerCase(),u=$('#unitFilter').value;const rows=state.supply.filter(x=>x.stock_tracking_active).filter(x=>{const name=`${x.Name||x.name||''} ${x.main_category||x.category||''}`.toLowerCase();return(!q||name.includes(q))&&(!u||normalizeUnit(x.Unit||x.unit)===u)});$('#dataRows').innerHTML=stockRows(rows)||`<tr><td colspan="7" class="empty">No stock found.</td></tr>`}
function renderVendors(){const active=state.vendors.filter(v=>v.is_active!==false),withPhone=active.filter(v=>v.phone||v.mobile),withEmail=active.filter(v=>v.email),used=new Set(state.bills.map(b=>String(b.vendor||b.vendor_name||b.Vendor||'').toLowerCase()).filter(Boolean));$('#content').innerHTML=hero()+stats([['Active vendors',active.length],['With phone',withPhone.length],['With email',withEmail.length],['Used in bills',used.size]])+`<section class="card toolbar"><label class="field"><span>Search</span><input id="vendorSearch" name="vendorSearch" type="search" autocomplete="off" placeholder="Search vendor"></label></section>`+table([['Vendor'],['Phone'],['Email'],['TIN'],['Last purchase'],['Total purchases','num']],vendorRows(active));$('#vendorSearch').oninput=()=>{const q=$('#vendorSearch').value.toLowerCase(),rows=active.filter(v=>`${v.name||''} ${v.phone||''} ${v.email||''}`.toLowerCase().includes(q));$('#dataRows').innerHTML=vendorRows(rows)||`<tr><td colspan="6" class="empty">No vendors found.</td></tr>`}}
function vendorRows(rows){return rows.map(v=>{const vb=state.bills.filter(b=>String(b.vendor_id||'')===String(v.id)||String(b.vendor||b.vendor_name||b.Vendor||'').toLowerCase()===String(v.name||'').toLowerCase());return`<tr><td><strong>${esc(v.name||'Unnamed vendor')}</strong></td><td>${esc(v.phone||v.mobile||'—')}</td><td>${esc(v.email||'—')}</td><td>${esc(v.tin||v.TIN||'—')}</td><td>${esc(String(vb[0]?.bill_day||vb[0]?.bill_date||vb[0]?.['Bill Date']||'—').slice(0,10))}</td><td class="num">${vb.length}</td></tr>`}).join('')}
function renderBills(){const total=state.bills.reduce((a,b)=>a+num(b.net_amount??b.amount??b.Amount),0);$('#content').innerHTML=hero(canWrite()?'<button class="btn primary" id="newBill">＋ New Bill</button>':'')+stats([['Bills',state.bills.length],['Vendors',state.vendors.length],['Live items',state.supply.filter(x=>x.stock_tracking_active).length],['Total value',money(total)]])+`<section class="card toolbar"><label class="field"><span>Search</span><input id="billSearch" name="billSearch" type="search" autocomplete="off" placeholder="Vendor or invoice"></label><label class="field"><span>Vendor</span><select id="billVendor" name="billVendor" autocomplete="off"><option value="">All vendors</option>${state.vendors.map(v=>`<option>${esc(v.name)}</option>`).join('')}</select></label><label class="field"><span>Status</span><select id="billStatus" name="billStatus" autocomplete="off"><option value="">All status</option><option>Pending</option><option>Paid</option><option>Recorded</option></select></label></section>`+table([['Date'],['Invoice'],['Vendor'],['Amount','num'],['Payment'],['Status']],billRows(state.bills));['billSearch','billVendor','billStatus'].forEach(id=>$(`#${id}`).oninput=drawBills);if($('#newBill'))$('#newBill').onclick=openBill}
function billRows(rows){return rows.map(b=>`<tr><td>${esc(String(b.bill_day||b.bill_date||b['Bill Date']||'—').slice(0,10))}</td><td><strong>${esc(b.bill_no||b.invoice_number||b['Bill No']||'#'+b.id)}</strong></td><td>${esc(b.vendor||b.vendor_name||b.Vendor||'Unknown')}</td><td class="num">${money(b.net_amount??b.amount??b.Amount)}</td><td>${esc(b.payment_status||'Recorded')}</td><td><span class="badge ${String(b.payment_status).toLowerCase()==='paid'?'good':'warn'}">${esc(b.approval_status||b.payment_status||'Recorded')}</span></td></tr>`).join('')}
function drawBills(){const q=$('#billSearch').value.toLowerCase(),v=$('#billVendor').value,s=$('#billStatus').value;const rows=state.bills.filter(b=>{const vendor=String(b.vendor||b.vendor_name||b.Vendor||''),invoice=String(b.bill_no||b.invoice_number||b['Bill No']||''),status=String(b.approval_status||b.payment_status||'Recorded');return(!q||`${vendor} ${invoice}`.toLowerCase().includes(q))&&(!v||vendor===v)&&(!s||status===s||String(b.payment_status||'')===s)});$('#dataRows').innerHTML=billRows(rows)||`<tr><td colspan="6" class="empty">No bills found.</td></tr>`}
const priceDiff=x=>x.price_difference!=null?num(x.price_difference):num(x.latest_unit_rate??x.latest_price??x.Rate??x.rate)-num(x.previous_unit_rate??x.previous_price);
function renderPrices(){const rows=state.prices.length?state.prices:state.supply;const changed=rows.filter(x=>priceDiff(x)!==0),inc=rows.filter(x=>priceDiff(x)>0),dec=rows.filter(x=>priceDiff(x)<0);$('#content').innerHTML=hero()+stats([['Products',rows.length],['Changed',changed.length],['Increased',inc.length],['Decreased',dec.length]])+filters('Search product or vendor','priceSearch',true,false)+table([['Product'],['Vendor'],['Unit'],['Latest price','num'],['Previous','num'],['Difference','num'],['Last purchase']],priceRows(rows));bindFilters('prices',drawPrices)}
function priceRows(rows){return rows.map(x=>{const latest=num(x.latest_unit_rate??x.latest_price??x.Rate??x.rate),prev=num(x.previous_unit_rate??x.previous_price),diff=priceDiff(x);return`<tr><td><strong>${esc(x.item_name||x.product_name||x.Name||x.name||'Unnamed')}</strong></td><td>${esc(x.latest_vendor_name||x.latest_vendor||x.vendor||'—')}</td><td>${normalizeUnit(x.stock_unit||x.unit||x.Unit)}</td><td class="num">${money(latest)}</td><td class="num">${prev?money(prev):'—'}</td><td class="num"><span class="badge ${diff>0?'bad':diff<0?'good':''}">${diff>0?'+':''}${money(diff)}</span></td><td>${esc(String(x.latest_purchase_date||x.last_purchase_date||x.updated_at||'—').slice(0,10))}</td></tr>`}).join('')}
function drawPrices(){const q=$('#priceSearch').value.toLowerCase(),u=$('#unitFilter').value,rows=(state.prices.length?state.prices:state.supply).filter(x=>{const text=`${x.item_name||x.product_name||x.Name||x.name||''} ${x.latest_vendor_name||x.latest_vendor||x.vendor||''}`.toLowerCase();return(!q||text.includes(q))&&(!u||normalizeUnit(x.stock_unit||x.unit||x.Unit)===u)});$('#dataRows').innerHTML=priceRows(rows)||`<tr><td colspan="7" class="empty">No prices found.</td></tr>`}
function filters(ph,id,units,status){return`<section class="card toolbar"><label class="field"><span>Search</span><input id="${id}" name="${id}" type="search" autocomplete="off" placeholder="${ph}"></label>${units?`<label class="field"><span>Unit</span><select id="unitFilter" name="unitFilter" autocomplete="off"><option value="">All units</option>${CANONICAL_UNITS.map(u=>`<option>${u}</option>`).join('')}</select></label>`:''}${status?`<label class="field"><span>Status</span><select id="statusFilter" name="statusFilter" autocomplete="off"><option value="">All status</option><option value="healthy">Healthy</option><option value="low">Low stock</option><option value="inactive">Not live</option></select></label>`:''}</section>`}
function bindFilters(kind,fn){const ids=kind==='inventory'?['inventorySearch','unitFilter','statusFilter']:kind==='stock'?['stockSearch','unitFilter']:['priceSearch','unitFilter'];ids.forEach(id=>$(`#${id}`).oninput=fn);document.querySelector('tbody').id='dataRows'}
function setModalTitle(kicker,title){$('.dialog-head .kicker').textContent=kicker;$('.dialog-head h2').textContent=title}
function openBill(){setModalTitle('New purchase','Purchase Bill');state.items=[{description:'',supply_id:'',quantity:1,unit:'PCS',unit_rate:0,gst_rate:8}];$('#modal').classList.remove('hidden');drawBillForm()}
function openStockCount(){setModalTitle('Stock setup','Start Stock Count');$('#modalBody').innerHTML=`<form id="stockCountForm"><p class="form-help">Enter the physical opening quantity and minimum level for each product. Saving activates stock tracking in one transaction.</p><div class="stock-count-list">${state.supply.map(x=>`<div class="stock-count-row" data-id="${x.id}"><div><strong>${esc(x.Name||x.name||'Unnamed')}</strong><small>${normalizeUnit(x.Unit||x.unit)} · ${esc(x.main_category||x.category||'Uncategorised')}</small></div><label class="field"><span>Opening stock</span><input data-stock type="number" min="0" step=".0001" value="${num(x.stock??x.current_stock)}" required></label><label class="field"><span>Minimum</span><input data-min type="number" min="0" step=".0001" value="${num(x.minimum_stock)}" required></label><label class="stock-toggle"><input data-active type="checkbox" ${x.stock_tracking_active?'checked':'checked'}><span>Track</span></label></div>`).join('')}</div><div id="stockCountError" class="error hidden"></div><div class="actions form-actions"><button type="button" class="btn" id="cancelStockCount">Cancel</button><button class="btn primary" id="saveStockCount">Activate Stock</button></div></form>`;$('#modal').classList.remove('hidden');$('#cancelStockCount').onclick=closeBill;$('#stockCountForm').onsubmit=saveStockCount}
async function saveStockCount(e){e.preventDefault();const rows=[...document.querySelectorAll('.stock-count-row')],payload=rows.map(row=>({id:Number(row.dataset.id),stock:num(row.querySelector('[data-stock]').value),minimum_stock:num(row.querySelector('[data-min]').value),active:row.querySelector('[data-active]').checked}));if(payload.some(x=>x.stock<0||x.minimum_stock<0)){showStockCountError('Stock and minimum values cannot be negative.');return}const button=$('#saveStockCount');button.disabled=true;button.textContent='Activating…';const{error}=await sb.rpc('start_stock_count',{p_counts:payload});button.disabled=false;button.textContent='Activate Stock';if(error){showStockCountError(error.message);return}closeBill();state.errors=[];await load();render()}
function showStockCountError(t){$('#stockCountError').textContent=t;$('#stockCountError').classList.remove('hidden')}
function drawBillForm(){$('#modalBody').innerHTML=`<form id="billForm"><div class="form-grid"><label class="field"><span>Date</span><input id="fDate" name="date" type="date" autocomplete="off" value="${new Date().toISOString().slice(0,10)}" required></label><label class="field"><span>Vendor</span><select id="fVendor" name="vendor" autocomplete="organization" required><option value="">Select vendor</option>${state.vendors.map(v=>`<option value="${v.id}" data-name="${esc(v.name)}">${esc(v.name)}</option>`).join('')}</select></label><label class="field"><span>Bill number</span><input id="fNumber" name="invoiceNumber" autocomplete="off" required></label><label class="field span-all"><span>Notes</span><textarea id="fNotes" name="notes" autocomplete="off"></textarea></label></div><div class="actions"><button type="button" class="btn" id="addItem">＋ Add Item</button></div><div class="items" id="billItems"></div><div class="totals"><div class="total"><span>Subtotal</span><strong id="sub">MVR 0.00</strong></div><div class="total"><span>GST</span><strong id="gst">MVR 0.00</strong></div><div class="total"><span>Net</span><strong id="net">MVR 0.00</strong></div></div><div id="billError" class="error hidden"></div><div class="actions" style="justify-content:flex-end;margin-top:16px"><button type="button" class="btn" id="cancelBill">Cancel</button><button class="btn primary" id="saveBill">Save Bill</button></div></form>`;drawItems();$('#addItem').onclick=()=>{state.items.push({description:'',supply_id:'',quantity:1,unit:'PCS',unit_rate:0,gst_rate:8});drawItems()};$('#cancelBill').onclick=closeBill;$('#billForm').onsubmit=saveBill}
function drawItems(){$('#billItems').innerHTML=state.items.map((x,i)=>`<div class="item-row"><label class="field"><span>Description</span><input data-i="${i}" data-f="description" name="description${i}" autocomplete="off" value="${esc(x.description)}" required></label><label class="field"><span>Stock item</span><select data-i="${i}" data-f="supply_id" name="stockItem${i}" autocomplete="off" required><option value="">Select</option>${state.supply.filter(s=>s.stock_tracking_active).map(s=>`<option value="${s.id}" ${String(s.id)===String(x.supply_id)?'selected':''}>${esc(s.Name||s.name)}</option>`).join('')}</select></label><label class="field"><span>Qty</span><input data-i="${i}" data-f="quantity" name="quantity${i}" type="number" min=".0001" step=".0001" autocomplete="off" value="${x.quantity}"></label><label class="field"><span>Unit</span><select data-i="${i}" data-f="unit" name="unit${i}" autocomplete="off">${CANONICAL_UNITS.map(u=>`<option ${u===normalizeUnit(x.unit)?'selected':''}>${u}</option>`).join('')}</select></label><label class="field"><span>Rate</span><input data-i="${i}" data-f="unit_rate" name="rate${i}" type="number" min="0" step=".01" autocomplete="off" value="${x.unit_rate}"></label><label class="field"><span>GST %</span><input data-i="${i}" data-f="gst_rate" name="gst${i}" type="number" min="0" max="100" step=".01" autocomplete="off" value="${x.gst_rate}"></label><button type="button" class="btn" data-remove="${i}" ${state.items.length===1?'disabled':''}>Remove</button></div>`).join('');document.querySelectorAll('[data-f]').forEach(el=>el.oninput=el.onchange=()=>{const i=+el.dataset.i,f=el.dataset.f;state.items[i][f]=el.value;if(f==='supply_id'){const s=state.supply.find(z=>String(z.id)===String(el.value));if(s){state.items[i].description=s.Name||s.name;state.items[i].unit=normalizeUnit(s.Unit||s.unit);state.items[i].unit_rate=num(s.Rate||s.rate||s.latest_price)}drawItems()}else totals()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.items.splice(+b.dataset.remove,1);drawItems()});totals()}
function totals(){let sub=0,gst=0;state.items.forEach(x=>{const line=num(x.quantity)*num(x.unit_rate);sub+=line;gst+=line*num(x.gst_rate)/100});$('#sub').textContent=money(sub);$('#gst').textContent=money(gst);$('#net').textContent=money(sub+gst)}
async function saveBill(e){e.preventDefault();const o=$('#fVendor').selectedOptions[0],payload=state.items.map((x,i)=>({description:String(x.description).trim(),supply_id:x.supply_id,quantity:num(x.quantity),unit:normalizeUnit(x.unit),unit_rate:num(x.unit_rate),gst_rate:num(x.gst_rate),sort_order:i+1}));if(payload.some(x=>!x.description||!x.supply_id||x.quantity<=0)){showBillError('Complete every item.');return}const bill={bill_day:$('#fDate').value,vendor_id:$('#fVendor').value,vendor:o?.dataset.name||'',bill_no:$('#fNumber').value.trim(),notes:$('#fNotes').value.trim(),currency:'MVR',payment_status:'Pending',approval_status:state.role==='staff'?'draft':'approved'};$('#saveBill').disabled=true;const{error}=await sb.rpc('create_bill_transaction',{p_bill:bill,p_items:payload});$('#saveBill').disabled=false;if(error){showBillError(error.message);return}closeBill();await load();render()}
function showBillError(t){$('#billError').textContent=t;$('#billError').classList.remove('hidden')}
function closeBill(){$('#modal').classList.add('hidden')}
async function start(session){state.session=session;setAuth(false);$('#accountEmail').textContent=session.user.email||'';const r=await sb.from('user_roles').select('role').eq('user_id',session.user.id).eq('is_active',true).maybeSingle();state.role=String(r.data?.role||'viewer').toLowerCase();$('#accountRole').textContent=state.role.toUpperCase();await load();go((location.hash||'#inventory').slice(1))}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').classList.add('hidden');const b=$('#loginButton');b.disabled=true;b.textContent='Signing in…';const{data,error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});b.disabled=false;b.textContent='Sign in';if(error){$('#loginError').textContent=error.message;$('#loginError').classList.remove('hidden');return}await start(data.session)};
$('#logout').onclick=async()=>{await sb.auth.signOut();setAuth(true)};document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));$('#mobileMenu').onclick=()=>{const route=prompt('Open: inventory, vendors, stock, bills, prices',state.route);if(route)go(route.toLowerCase())};$('#closeModal').onclick=closeBill;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeBill()};window.addEventListener('hashchange',()=>go(location.hash.slice(1)));const{data:{session}}=await sb.auth.getSession();session?await start(session):setAuth(true);
