import {store,escapeHtml} from './store.js';
import {signIn,signOut,restoreSession,loadBills} from './data.js';
import {startRouter,navigate} from './router.js?v=5.1.2';
const $=s=>document.querySelector(s);
const navGroups=[['Overview',[['dashboard','Dashboard','fa-table-cells-large']]],['Procurement',[['bills','Bills','fa-file-invoice'],['rates','Price Intelligence','fa-chart-line','admin'],['products','Products','fa-box'],['vendors','Vendors','fa-building']]],['Analytics',[['reports','Reports','fa-chart-pie']]],['Administration',[['settings','Settings','fa-gear'],['admin','Admin & users','fa-users-gear','admin']]];
const health={version:'5.1.2',booted:false,authenticated:false,dataLoaded:false,error:null,runtimeErrors:[],startedAt:new Date().toISOString()};window.app={store,health};
function recordRuntimeError(error,source='runtime'){const message=error?.message||String(error||'Unknown error');health.error=message;health.runtimeErrors.push({source,message,time:new Date().toISOString()});if(health.runtimeErrors.length>20)health.runtimeErrors.shift();console.error(`[${source}]`,error)}
window.addEventListener('error',event=>recordRuntimeError(event.error||event.message,'window.error'));
window.addEventListener('unhandledrejection',event=>recordRuntimeError(event.reason,'unhandledrejection'));
function removeGeneratedPlaceholders(){try{const key='bills.productMetadata.v3',meta=JSON.parse(localStorage.getItem(key)||'{}');let changed=false;for(const value of Object.values(meta)){if(value?.imageSource==='generated'||String(value?.photo||'').includes('Generated%20catalogue%20illustration')){delete value.photo;delete value.imageSource;changed=true}}if(changed)localStorage.setItem(key,JSON.stringify(meta))}catch(error){recordRuntimeError(error,'catalog-cleanup')}}
function buildNav(){$('#nav').innerHTML=navGroups.map(([group,items])=>{const visible=items.filter(([, , ,role])=>!role||store.role===role);if(!visible.length)return'';return`<div class="nav-group"><div class="nav-label">${group}</div>${visible.map(([route,label,icon])=>`<a href="#${route}" data-route="${route}" title="${label}"><i class="fa-solid ${icon}" aria-hidden="true"></i><span>${label}</span></a>`).join('')}</div>`}).join('')}
function setSidebar(open){const sidebar=$('#sidebar'),backdrop=$('#sidebarBackdrop'),button=$('#menuBtn');sidebar?.classList.toggle('open',open);backdrop?.classList.toggle('visible',open);backdrop?.classList.toggle('hidden',!open);document.body.classList.toggle('nav-open',open);button?.setAttribute('aria-expanded',String(open))}
const closeSidebar=()=>setSidebar(false),toggleSidebar=()=>setSidebar(!$('#sidebar')?.classList.contains('open'));
function setCollapsed(collapsed){$('#appView')?.classList.toggle('sidebar-collapsed',collapsed);$('#collapseSidebar')?.setAttribute('aria-pressed',String(collapsed));$('#collapseSidebar i')?.classList.toggle('fa-angles-right',collapsed);$('#collapseSidebar i')?.classList.toggle('fa-angles-left',!collapsed);try{localStorage.setItem('bills.sidebarCollapsed',collapsed?'1':'0')}catch(error){recordRuntimeError(error,'sidebar-preference')}}
function hideAuthLoader(){$('#authLoader')?.classList.add('hidden');document.body.classList.remove('auth-pending')}
function showAuthLoader(message='Checking your secure session…'){const loader=$('#authLoader');if(loader){loader.classList.remove('hidden');const copy=loader.querySelector('[data-auth-message]');if(copy)copy.textContent=message}$('#loginView').classList.add('hidden');$('#appView').classList.add('hidden');document.body.classList.add('auth-pending')}
function showApp(){buildNav();hideAuthLoader();$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');const email=store.user?.email||'Signed in',role=store.role.toUpperCase(),initial=email.charAt(0).toUpperCase();$('#roleLabel').textContent=role;$('#emailLabel').textContent=email;$('#avatar').textContent=initial;$('#sideEmail').textContent=email;$('#sideRole').textContent=role;$('#sideAvatar').textContent=initial;health.authenticated=true}
function showLogin(message=''){closeSidebar();hideAuthLoader();$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginNotice').textContent=message;health.authenticated=false}
function showWorkspaceError(error){const message=error?.message||String(error||'Unknown error');recordRuntimeError(error,'workspace');$('#content').innerHTML=`<section class="panel"><div class="empty"><h2>Workspace could not finish loading</h2><p>${escapeHtml(message)}</p><button class="btn" id="retryWorkspace" type="button">Retry</button></div></section>`;$('#retryWorkspace')?.addEventListener('click',()=>loadAndStart())}
async function loadAndStart(){const content=$('#content');content.replaceChildren();content.setAttribute('aria-busy','true');try{await loadBills();health.dataLoaded=true;health.error=null;startRouter()}catch(error){health.dataLoaded=false;showWorkspaceError(error);throw error}finally{content.removeAttribute('aria-busy')}}
async function boot(){removeGeneratedPlaceholders();showAuthLoader();buildNav();let collapsed=false;try{collapsed=localStorage.getItem('bills.sidebarCollapsed')==='1'}catch(error){recordRuntimeError(error,'sidebar-preference-read')}setCollapsed(collapsed);$('#menuBtn').onclick=toggleSidebar;$('#sidebarClose').onclick=closeSidebar;$('#sidebarBackdrop').onclick=closeSidebar;$('#collapseSidebar').onclick=()=>setCollapsed(!$('#appView').classList.contains('sidebar-collapsed'));document.addEventListener('click',event=>{const trigger=event.target.closest('a[data-route],button[data-route]');if(!trigger)return;event.preventDefault();closeSidebar();navigate(trigger.dataset.route)});window.addEventListener('hashchange',closeSidebar);window.addEventListener('resize',()=>{if(window.innerWidth>820)closeSidebar()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeSidebar()});$('#logoutBtn').onclick=async()=>{const button=$('#logoutBtn');button.disabled=true;showAuthLoader('Signing out securely…');try{await signOut();health.dataLoaded=false;showLogin()}catch(error){recordRuntimeError(error,'sign-out');showLogin(error?.message||'Sign out failed.')}finally{button.disabled=false}};$('#footerYear').textContent=new Date().getFullYear();$('#loginForm').onsubmit=async event=>{event.preventDefault();const submit=event.submitter;$('#loginNotice').textContent='Signing in…';if(submit)submit.disabled=true;try{await signIn($('#loginName').value,$('#loginPassword').value);showApp();$('#loginNotice').textContent='';await loadAndStart().catch(()=>{})}catch(error){recordRuntimeError(error,'sign-in');showLogin(error?.message||'Sign in failed.')}finally{if(submit)submit.disabled=false}};try{const user=await restoreSession();if(!user){showLogin();health.booted=true;return}showApp();await loadAndStart().catch(()=>{})}catch(error){recordRuntimeError(error,'session-restore');showLogin('Your saved session expired. Please sign in again.')}finally{health.booted=true}}
boot();