import {store,money,escapeHtml,text,number,billDate,vendor,amount,status,billNo,productOf,itemOf,get} from './store.js';
import {saveBillRecords,updateBill,deleteBill} from './data.js';

const $=s=>document.querySelector(s);
const content=()=>$('#content');
const header=(title,subtitle,actions='')=>`<header class="page-head"><div><h1>${escapeHtml(title)}</h1><p>${escapeHtml(subtitle)}</p></div>${actions?`<div class="actions">${actions}</div>`:''}</header>`;
const kpi=(label,value,meta='')=>`<article class="kpi"><span>${escapeHtml(label)}</span><strong>${value}</strong>${meta?`<small>${escapeHtml(meta)}</small>`:''}</article>`;
const today=()=>new Date().toISOString().slice(0,10);
const thisMonth=()=>today().slice(0,7);
const unique=arr=>[...new Set(arr.filter(Boolean))];

function bindRoute(root=content()){root.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>location.hash=`#${el.dataset.route}`)}

export function dashboardPage(){
  const rows=store.rows,total=rows.reduce((s,b)=>s+amount(b),0),paid=rows.filter(b=>status(b).toLowerCase()==='paid'),pending=rows.filter(b=>status(b).toLowerCase()!=='paid');
  const suppliers=unique(rows.map(vendor));const products=unique(rows.map(productOf));const monthRows=rows.filter(b=>billDate(b).startsWith(thisMonth()));
  const categories=new Map();rows.forEach(b=>{const cat=text(get(itemOf(b),'category')||get(b,'category'))||'Other';categories.set(cat,(categories.get(cat)||0)+amount(b))});
  const top=[...categories.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4);const max=Math.max(1,...top.map(x=>x[1]));
  const years=new Map();rows.forEach(b=>{const y=billDate(b).slice(0,4);if(/^\d{4}$/.test(y))years.set(y,(years.get(y)||0)+amount(b))});const yearList=[...years.entries()].sort((a,b)=>a[0].localeCompare(b[0]));const yearMax=Math.max(1,...yearList.map(x=>x[1]));
  content().innerHTML=`${header('Procurement Dashboard','Management view of purchasing, payments, suppliers and orders.','<button class="btn" data-route="new">+ New Bill</button>')}
  <section class="grid-4">${kpi('Procurement value',money(total),`${money(monthRows.reduce((s,b)=>s+amount(b),0))} this month`)}${kpi('Payment health',money(paid.reduce((s,b)=>s+amount(b),0)),`${pending.length} pending records`)}${kpi('Supplier coverage',suppliers.length.toLocaleString(),`${products.length} tracked products`)}${kpi('Purchase orders',rows.length.toLocaleString(),`${monthRows.length} this month`)}</section>
  <section class="grid-2"><article class="card"><header class="card-head"><h2>Spend composition</h2><small>Top categories</small></header><div class="card-body progress-list">${top.map(([name,value])=>`<div class="progress-row"><span>${escapeHtml(name)}</span><div class="track"><span style="width:${value/max*100}%"></span></div><strong>${money(value)}</strong></div>`).join('')||'<div class="empty">No category data.</div>'}</div></article>
  <article class="card"><header class="card-head"><h2>Revenue history</h2><small>Recorded procurement by year</small></header><div class="card-body progress-list">${yearList.map(([year,value])=>`<div class="progress-row"><span>${year}</span><div class="track"><span style="width:${value/yearMax*100}%"></span></div><strong>${money(value)}</strong></div>`).join('')||'<div class="empty">No dated records.</div>'}</div></article></section>`;
  bindRoute();
}

export function billsPage(){
  const rows=[...store.rows].sort((a,b)=>billDate(b).localeCompare(billDate(a)));
  content().innerHTML=`${header('Bills','Search, review and manage supplier purchases.','<button class="btn" data-route="new">+ New Bill</button>')}
  <section class="toolbar"><input id="billSearch" placeholder="Search invoice, item or vendor"><select id="billVendor"><option value="">All vendors</option>${unique(rows.map(vendor)).sort().map(v=>`<option>${escapeHtml(v)}</option>`).join('')}</select><select id="billStatus"><option value="">All statuses</option><option>Paid</option><option>Pending</option></select><input id="billDate" type="date"></section>
  <section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Invoice</th><th>Bill date</th><th>Description</th><th>Vendor</th><th>Status</th><th>Amount</th><th>Actions</th></tr></thead><tbody id="billRows"></tbody></table></div><footer class="pager"><span id="pageMeta"></span><div class="actions"><button class="btn secondary small" id="prevPage">Previous</button><button class="btn secondary small" id="nextPage">Next</button></div></footer></section>`;
  const draw=()=>{
    const q=text($('#billSearch').value).toLowerCase(),v=$('#billVendor').value,s=$('#billStatus').value,d=$('#billDate').value;
    const filtered=rows.filter(b=>(!q||`${billNo(b)} ${vendor(b)} ${productOf(b)}`.toLowerCase().includes(q))&&(!v||vendor(b)===v)&&(!s||status(b).toLowerCase()===s.toLowerCase())&&(!d||billDate(b)===d));
    const pages=Math.max(1,Math.ceil(filtered.length/store.pageSize));store.page=Math.min(Math.max(1,store.page),pages);const start=(store.page-1)*store.pageSize,slice=filtered.slice(start,start+store.pageSize);
    $('#billRows').innerHTML=slice.map(b=>{const item=itemOf(b),pack=text(get(item,'pack_format','packing')),unit=text(get(item,'unit')),qty=number(get(item,'qty','quantity'));return `<tr><td><strong>${escapeHtml(billNo(b))}</strong></td><td>${escapeHtml(billDate(b)||'No date')}<br><small>${escapeHtml(String(get(b,'updated_at','created_at')||'').slice(0,16).replace('T',' '))}</small></td><td><strong>${escapeHtml(productOf(b))}</strong><br><small>${escapeHtml([pack,unit,qty?`Qty ${qty}`:''].filter(Boolean).join(' · '))}</small></td><td>${escapeHtml(vendor(b))}</td><td><span class="badge ${status(b).toLowerCase()==='paid'?'paid':'pending'}">${escapeHtml(status(b))}</span></td><td><strong>${money(amount(b))}</strong></td><td><div class="actions"><button class="btn secondary small" data-edit="${b.id}">Edit</button>${store.role==='admin'?`<button class="btn danger small" data-delete="${b.id}">Delete</button>`:''}</div></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No bills match these filters.</td></tr>';
    $('#pageMeta').textContent=`${filtered.length?start+1:0}–${Math.min(start+store.pageSize,filtered.length)} of ${filtered.length}`;$('#prevPage').disabled=store.page<=1;$('#nextPage').disabled=store.page>=pages;
    document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>{store.editing=rows.find(b=>String(b.id)===String(x.dataset.edit));location.hash='#new'});
    document.querySelectorAll('[data-delete]').forEach(x=>x.onclick=async()=>{if(!confirm('Delete this bill?'))return;await deleteBill(x.dataset.delete);billsPage()});
  };
  ['billSearch','billVendor','billStatus','billDate'].forEach(id=>$('#'+id).addEventListener(id==='billSearch'?'input':'change',()=>{store.page=1;draw()}));$('#prevPage').onclick=()=>{store.page--;draw()};$('#nextPage').onclick=()=>{store.page++;draw()};bindRoute();draw();
}

function parsePack(pack,unit,qty){const p=text(pack).toLowerCase().replace(/\s+/g,''),u=text(unit).toUpperCase();let count=1,size=1,kind=u;const m=p.match(/^(\d+(?:\.\d+)?)x(\d+(?:\.\d+)?)(kg|g|l|ml|pcs?)$/);if(m){count=number(m[1]);size=number(m[2]);kind=m[3].toUpperCase()}else{const single=p.match(/^(\d+(?:\.\d+)?)(kg|g|l|ml|pcs?)$/);if(single){size=number(single[1]);kind=single[2].toUpperCase()}}let base=count*size*qty;if(kind==='KG')base*=1000;if(kind==='L')base*=1000;return{base,baseUnit:['KG','G'].includes(kind)?'G':['L','ML'].includes(kind)?'ML':'PCS'}}
function rowTemplate(item={}){return `<div class="bill-row"><label>Item<input data-field="description" value="${escapeHtml(get(item,'description','product','name'))}"></label><label>Packing<input data-field="pack" value="${escapeHtml(get(item,'pack_format','packing')||'10x500g')}"></label><label>Unit<select data-field="unit">${['CSE','KG','G','L','ML','PCS','CTN','DOZ','PKT'].map(u=>`<option ${text(get(item,'unit')).toUpperCase()===u?'selected':''}>${u}</option>`).join('')}</select></label><label>Qty<input data-field="qty" type="number" min="0" step="any" value="${number(get(item,'qty','quantity'))||1}"></label><label>Row total<input data-field="total" type="number" min="0" step="any" value="${number(get(item,'row_total','total','rate'))}"></label><label>GST %<input data-field="gst" type="number" min="0" step="any" value="${number(get(item,'gst'))}"></label><button class="btn danger small" data-remove type="button">×</button></div>`}
export function newBillPage(){
  const editing=store.editing,existing=editing?(Array.isArray(editing.items)&&editing.items.length?editing.items:[itemOf(editing)]):[];
  content().innerHTML=`${header(editing?'Edit Bill':'New Bill',editing?'Update the selected procurement record.':'Record a supplier purchase.','<button class="btn secondary" data-route="bills">Close</button>')}
  <form id="billForm" class="bill-form"><section class="card"><header class="card-head"><h2>Bill information</h2></header><div class="card-body form-grid"><label>Vendor<input id="vendor" required value="${escapeHtml(editing?vendor(editing):'')}"></label><label>Bill date<input id="date" type="date" required value="${escapeHtml(editing?billDate(editing):today())}"></label><label>Bill no.<input id="billNo" value="${escapeHtml(editing?billNo(editing)==='—'?'':billNo(editing):'')}"></label><label>Payment status<select id="payment"><option ${editing&&status(editing)==='Pending'?'selected':''}>Pending</option><option ${editing&&status(editing)==='Paid'?'selected':''}>Paid</option></select></label><label>Payment method<input id="method" value="${escapeHtml(editing?text(get(editing,'payment_method','method')):'')}"></label><label>Reference / description<input id="description" value="${escapeHtml(editing?text(get(editing,'description','notes')):'')}"></label></div></section>
  <section class="card"><header class="card-head"><h2>Bill items</h2><button class="btn secondary small" id="addRow" type="button">Add row</button></header><div class="bill-items" id="billItems">${(existing.length?existing:[{},{},{}]).map(rowTemplate).join('')}</div></section>
  <section class="card"><div class="card-body bill-footer"><label>Notes<textarea id="notes">${escapeHtml(editing?text(get(editing,'notes')):'')}</textarea></label><div><div class="totals"><div><span>Subtotal</span><strong id="subtotal">MVR 0.00</strong></div><div><span>GST total</span><strong id="gstTotal">MVR 0.00</strong></div><div class="grand"><span>Total due</span><strong id="grandTotal">MVR 0.00</strong></div></div><div class="actions" style="margin-top:16px"><button class="btn" type="submit">Review & save</button><button class="btn secondary" type="button" data-route="bills">Cancel</button></div></div></div></section></form>`;
  const items=()=>[...document.querySelectorAll('.bill-row')].map(row=>({row,description:text(row.querySelector('[data-field="description"]').value),pack:text(row.querySelector('[data-field="pack"]').value),unit:row.querySelector('[data-field="unit"]').value,qty:number(row.querySelector('[data-field="qty"]').value),total:number(row.querySelector('[data-field="total"]').value),gst:number(row.querySelector('[data-field="gst"]').value)})).filter(i=>i.description||i.total);
  const totals=()=>{const list=items(),sub=list.reduce((s,i)=>s+i.total,0),gst=list.reduce((s,i)=>s+i.total*i.gst/100,0);$('#subtotal').textContent=money(sub);$('#gstTotal').textContent=money(gst);$('#grandTotal').textContent=money(sub+gst);return{sub,gst,grand:sub+gst,list}};
  const bindRows=()=>{document.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>{if(document.querySelectorAll('.bill-row').length>1)btn.closest('.bill-row').remove();totals()});document.querySelectorAll('.bill-row input,.bill-row select').forEach(el=>el.addEventListener('input',totals))};
  $('#addRow').onclick=()=>{$('#billItems').insertAdjacentHTML('beforeend',rowTemplate({}));bindRows();totals()};bindRows();totals();bindRoute();
  $('#billForm').onsubmit=e=>{e.preventDefault();const summary=totals();if(!text($('#vendor').value)||!$('#date').value||!summary.list.length){alert('Vendor, bill date and at least one item are required.');return}showReview(summary)};
  function showReview(summary){const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<section class="modal-card"><header class="card-head"><h2>Review before saving</h2><button class="btn secondary small" data-close>Close</button></header><div class="card-body"><p><strong>${escapeHtml($('#vendor').value)}</strong> · ${escapeHtml($('#date').value)} · ${escapeHtml($('#billNo').value||'No bill number')}</p><div class="table-wrap" style="margin-top:16px"><table class="table"><thead><tr><th>Item</th><th>Packing</th><th>Unit</th><th>Qty</th><th>Base quantity</th><th>GST</th><th>Total</th></tr></thead><tbody>${summary.list.map(i=>{const p=parsePack(i.pack,i.unit,i.qty);return `<tr><td>${escapeHtml(i.description)}</td><td>${escapeHtml(i.pack)}</td><td>${escapeHtml(i.unit)}</td><td>${i.qty}</td><td>${p.base.toLocaleString('en-US')} ${p.baseUnit}</td><td>${i.gst}%</td><td>${money(i.total+i.total*i.gst/100)}</td></tr>`}).join('')}</tbody></table></div><div class="totals" style="margin-top:16px"><div><span>Subtotal</span><strong>${money(summary.sub)}</strong></div><div><span>GST</span><strong>${money(summary.gst)}</strong></div><div class="grand"><span>Total due</span><strong>${money(summary.grand)}</strong></div></div><div class="actions" style="margin-top:16px;justify-content:flex-end"><button class="btn secondary" data-close>Back to edit</button><button class="btn" data-confirm>Confirm & save</button></div></div></section>`;document.body.appendChild(modal);modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.remove());modal.querySelector('[data-confirm]').onclick=async()=>{const shared={bill_date:$('#date').value,bill_no:text($('#billNo').value),vendor:text($('#vendor').value),payment_status:$('#payment').value,payment_method:text($('#method').value),notes:text($('#notes').value),description:text($('#description').value)};try{if(editing){const i=summary.list[0],p=parsePack(i.pack,i.unit,i.qty);await updateBill(editing.id,{...shared,amount:i.total+i.total*i.gst/100,items:[{description:i.description,pack_format:i.pack,unit:i.unit,qty:i.qty,row_total:i.total,gst:i.gst,base_quantity:p.base,base_unit:p.baseUnit,unit_rate:p.base?i.total/p.base:0}]})}else{const records=summary.list.map(i=>{const p=parsePack(i.pack,i.unit,i.qty);return{...shared,amount:i.total+i.total*i.gst/100,items:[{description:i.description,pack_format:i.pack,unit:i.unit,qty:i.qty,row_total:i.total,gst:i.gst,base_quantity:p.base,base_unit:p.baseUnit,unit_rate:p.base?i.total/p.base:0}]}});await saveBillRecords(records)}store.editing=null;modal.remove();location.hash='#bills'}catch(error){alert(error.message)}}}
}

function productData(){const map=new Map();store.rows.forEach(b=>{const name=productOf(b),item=itemOf(b);if(!map.has(name))map.set(name,{name,suppliers:new Set(),records:0,lastPrice:0,pack:'',unit:''});const p=map.get(name);p.suppliers.add(vendor(b));p.records++;p.lastPrice=amount(b);p.pack=text(get(item,'pack_format','packing'));p.unit=text(get(item,'unit'))});return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
export function productsPage(){const data=productData();content().innerHTML=`${header('Products','Product catalogue generated from saved bill items.')}<section class="toolbar" style="grid-template-columns:1fr auto"><input id="productSearch" placeholder="Search products or suppliers"><span>${data.length} products</span></section><section class="catalog" id="catalog">${data.map(p=>`<article class="product-card" data-search="${escapeHtml(`${p.name} ${[...p.suppliers].join(' ')}`.toLowerCase())}"><div class="product-image">📦</div><div class="product-body"><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml([...p.suppliers].slice(0,2).join(', '))}</p><strong>${money(p.lastPrice)}</strong><small>${escapeHtml([p.pack,p.unit].filter(Boolean).join(' · '))}</small></div></article>`).join('')||'<div class="empty">No products available.</div>'}</section>`;$('#productSearch').oninput=e=>document.querySelectorAll('.product-card').forEach(card=>card.hidden=!card.dataset.search.includes(e.target.value.toLowerCase()))}
export function ratesPage(){const data=productData();content().innerHTML=`${header('Price Intelligence','Compare current product prices and supplier coverage.')}<section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Small image</th><th>Current price</th><th>Pack</th><th>Suppliers</th><th>Records</th></tr></thead><tbody>${data.map(p=>`<tr><td><strong>${escapeHtml(p.name)}</strong></td><td>📦</td><td>${money(p.lastPrice)}</td><td>${escapeHtml([p.pack,p.unit].filter(Boolean).join(' · '))}</td><td>${p.suppliers.size}</td><td>${p.records}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No price records.</td></tr>'}</tbody></table></div></section>`}
export function vendorsPage(){const map=new Map();store.rows.forEach(b=>{const n=vendor(b);if(!map.has(n))map.set(n,{name:n,bills:0,total:0,products:new Set()});const v=map.get(n);v.bills++;v.total+=amount(b);v.products.add(productOf(b))});const data=[...map.values()].sort((a,b)=>b.total-a.total);content().innerHTML=`${header('Vendors','Supplier directory and procurement performance.')}<section class="catalog">${data.map(v=>`<article class="product-card"><div class="product-image">🏢</div><div class="product-body"><h3>${escapeHtml(v.name)}</h3><p>${v.bills} bills · ${v.products.size} products</p><strong>${money(v.total)}</strong></div></article>`).join('')||'<div class="empty">No suppliers.</div>'}</section>`}
export function reportsPage(){const rows=store.rows,total=rows.reduce((s,b)=>s+amount(b),0),suppliers=unique(rows.map(vendor));const months=new Map();rows.forEach(b=>{const key=billDate(b).slice(0,7)||'Unknown';months.set(key,(months.get(key)||0)+amount(b))});const list=[...months.entries()].sort((a,b)=>b[0].localeCompare(a[0])).slice(0,12),max=Math.max(1,...list.map(x=>x[1]));content().innerHTML=`${header('Reports','Management analytics for spend, suppliers, products and tax.','<button class="btn secondary">Export summary</button>')}<section class="grid-4">${kpi('Total procurement',money(total))}${kpi('Bills recorded',rows.length.toLocaleString())}${kpi('Suppliers',suppliers.length.toLocaleString())}${kpi('GST recorded',money(rows.reduce((s,b)=>s+number(get(b,'gst_total','gst')),0)))}</section><section class="card"><header class="card-head"><h2>Spend trend</h2><small>By recorded month</small></header><div class="card-body progress-list">${list.map(([m,v])=>`<div class="progress-row"><span>${escapeHtml(m)}</span><div class="track"><span style="width:${v/max*100}%"></span></div><strong>${money(v)}</strong></div>`).join('')}</div></section>`}
export function settingsPage(){content().innerHTML=`${header('Settings','Configure workspace defaults.')}<section class="card"><header class="card-head"><h2>Workspace</h2></header><div class="card-body form-grid"><label>Business name<input value="White Saffron"></label><label>Currency<input value="MVR" disabled></label><label>Rows per page<select id="rowsPerPage"><option>20</option><option>50</option></select></label></div></section>`;$('#rowsPerPage').value=String(store.pageSize);$('#rowsPerPage').onchange=e=>store.pageSize=number(e.target.value)}
export function adminPage(){content().innerHTML=`${header('Admin & users','Current account and system status.')}<section class="grid-4">${kpi('Role',store.role.toUpperCase())}${kpi('Loaded records',store.rows.length.toLocaleString())}${kpi('Session',store.user?'Active':'Signed out')}${kpi('Database','Supabase','Connected through publishable client')}</section>`}
