import {store,money,escapeHtml,text,number,billDate,vendor,amount,status,billNo,productOf,itemOf,get} from './store.js';
import {saveBillRecords,updateBill,deleteBill} from './data.js';

const $=s=>document.querySelector(s);
const content=()=>$('#content');
const header=(title,subtitle,actions='')=>`<header class="page-head"><div><h1>${escapeHtml(title)}</h1><p>${escapeHtml(subtitle)}</p></div>${actions?`<div class="actions">${actions}</div>`:''}</header>`;
const kpi=(label,value,meta='')=>`<article class="kpi"><span>${escapeHtml(label)}</span><strong>${value}</strong>${meta?`<small>${escapeHtml(meta)}</small>`:''}</article>`;
const today=()=>new Date().toISOString().slice(0,10);
const thisMonth=()=>today().slice(0,7);
const unique=arr=>[...new Set(arr.filter(Boolean))];
const units=['BTL','ML','L','KG','G','PCS','CTN','DOZ','PKT'];
const methods=['Cash','Bank transfer','Card','Cheque','Credit'];

function bindRoute(root=content()){root.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>location.hash=`#${el.dataset.route}`)}
function canEdit(row){if(store.role==='admin')return true;const stamp=new Date(get(row,'created_at','updated_at')).getTime();return Number.isFinite(stamp)&&Date.now()-stamp<=86400000}
function vendorDirectory(){const map=new Map();store.rows.forEach(row=>{const name=vendor(row);if(!name||name==='Unknown supplier')return;if(!map.has(name))map.set(name,{name,tin:'',mobile:'',location:''});const entry=map.get(name);entry.tin||=text(get(row,'tin','vendor_tin'));entry.mobile||=text(get(row,'mobile','phone','vendor_mobile'));entry.location||=text(get(row,'location','address'))});return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}

export function dashboardPage(){
  const rows=store.rows,total=rows.reduce((s,b)=>s+amount(b),0),paid=rows.filter(b=>status(b).toLowerCase()==='paid'),pending=rows.filter(b=>status(b).toLowerCase()!=='paid');
  const suppliers=unique(rows.map(vendor)),products=unique(rows.map(productOf)),monthRows=rows.filter(b=>billDate(b).startsWith(thisMonth()));
  const categories=new Map();rows.forEach(b=>{const cat=text(get(itemOf(b),'category')||get(b,'category'))||'Other';categories.set(cat,(categories.get(cat)||0)+amount(b))});
  const top=[...categories.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4),max=Math.max(1,...top.map(x=>x[1]));
  const years=new Map();rows.forEach(b=>{const y=billDate(b).slice(0,4);if(/^\d{4}$/.test(y))years.set(y,(years.get(y)||0)+amount(b))});const yearList=[...years.entries()].sort((a,b)=>a[0].localeCompare(b[0])),yearMax=Math.max(1,...yearList.map(x=>x[1]));
  content().innerHTML=`${header('Procurement Dashboard','Management view of purchasing, payments, suppliers and orders.','<button class="btn" data-route="new">+ New Bill</button>')}<section class="grid-4">${kpi('Procurement value',money(total),`${money(monthRows.reduce((s,b)=>s+amount(b),0))} this month`)}${kpi('Payment health',money(paid.reduce((s,b)=>s+amount(b),0)),`${pending.length} pending records`)}${kpi('Supplier coverage',suppliers.length.toLocaleString(),`${products.length} tracked products`)}${kpi('Purchase orders',rows.length.toLocaleString(),`${monthRows.length} this month`)}</section><section class="grid-2"><article class="card"><header class="card-head"><h2>Spend composition</h2><small>Top categories</small></header><div class="card-body progress-list">${top.map(([name,value])=>`<div class="progress-row"><span>${escapeHtml(name)}</span><div class="track"><span style="width:${value/max*100}%"></span></div><strong>${money(value)}</strong></div>`).join('')||'<div class="empty">No category data.</div>'}</div></article><article class="card"><header class="card-head"><h2>Purchase history</h2><small>Recorded procurement by year</small></header><div class="card-body progress-list">${yearList.map(([year,value])=>`<div class="progress-row"><span>${year}</span><div class="track"><span style="width:${value/yearMax*100}%"></span></div><strong>${money(value)}</strong></div>`).join('')||'<div class="empty">No dated records.</div>'}</div></article></section>`;bindRoute();
}

export function billsPage(){
  const rows=[...store.rows].sort((a,b)=>billDate(b).localeCompare(billDate(a)));
  content().innerHTML=`${header('Bills','Search, review and manage supplier purchases.','<button class="btn" data-route="new">+ New Bill</button>')}<section class="toolbar"><input id="billSearch" placeholder="Search bill, item or vendor"><select id="billVendor"><option value="">All vendors</option>${unique(rows.map(vendor)).sort().map(v=>`<option>${escapeHtml(v)}</option>`).join('')}</select><select id="billStatus"><option value="">All statuses</option><option>Paid</option><option>Pending</option></select><input id="billDate" type="date"></section><section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Bill no.</th><th>Bill date / last edit</th><th>Product</th><th>Vendor</th><th>Status</th><th class="num">Amount</th><th class="action-col">Actions</th></tr></thead><tbody id="billRows"></tbody></table></div><footer class="pager"><span id="pageMeta"></span><div class="actions"><button class="btn secondary small" id="prevPage">Previous</button><button class="btn secondary small" id="nextPage">Next</button></div></footer></section>`;
  const draw=()=>{const q=text($('#billSearch').value).toLowerCase(),v=$('#billVendor').value,s=$('#billStatus').value,d=$('#billDate').value;const filtered=rows.filter(b=>(!q||`${billNo(b)} ${vendor(b)} ${productOf(b)}`.toLowerCase().includes(q))&&(!v||vendor(b)===v)&&(!s||status(b).toLowerCase()===s.toLowerCase())&&(!d||billDate(b)===d));const pages=Math.max(1,Math.ceil(filtered.length/store.pageSize));store.page=Math.min(Math.max(1,store.page),pages);const start=(store.page-1)*store.pageSize,slice=filtered.slice(start,start+store.pageSize);$('#billRows').innerHTML=slice.map(b=>{const item=itemOf(b),pack=text(get(item,'pack_format','packing')),unit=text(get(item,'unit')),qty=number(get(item,'qty','quantity')),updated=String(get(b,'updated_at','created_at')||'').slice(0,16).replace('T',' '),editable=canEdit(b);return `<tr><td><strong>${escapeHtml(billNo(b))}</strong></td><td><strong>${escapeHtml(billDate(b)||'No date')}</strong><small class="cell-meta">Last edit: ${escapeHtml(updated||'Not recorded')}</small></td><td><strong>${escapeHtml(productOf(b))}</strong><small class="cell-meta">${escapeHtml([pack,unit,qty?`Qty ${qty}`:''].filter(Boolean).join(' · '))}</small></td><td>${escapeHtml(vendor(b))}</td><td><span class="badge ${status(b).toLowerCase()==='paid'?'paid':'pending'}">${escapeHtml(status(b))}</span></td><td class="num"><strong>${money(amount(b))}</strong></td><td class="action-col"><div class="actions">${editable?`<button class="btn secondary small" data-edit="${b.id}">Edit</button>`:'<span class="locked">Locked</span>'}${store.role==='admin'?`<button class="btn danger small" data-delete="${b.id}">Delete</button>`:''}</div></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No bills match these filters.</td></tr>';$('#pageMeta').textContent=`${filtered.length?start+1:0}–${Math.min(start+store.pageSize,filtered.length)} of ${filtered.length}`;$('#prevPage').disabled=store.page<=1;$('#nextPage').disabled=store.page>=pages;document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>{store.editing=rows.find(b=>String(b.id)===String(x.dataset.edit));location.hash='#new'});document.querySelectorAll('[data-delete]').forEach(x=>x.onclick=async()=>{if(!confirm('Delete this bill?'))return;await deleteBill(x.dataset.delete);billsPage()})};
  ['billSearch','billVendor','billStatus','billDate'].forEach(id=>$('#'+id).addEventListener(id==='billSearch'?'input':'change',()=>{store.page=1;draw()}));$('#prevPage').onclick=()=>{store.page--;draw()};$('#nextPage').onclick=()=>{store.page++;draw()};bindRoute();draw();
}

function parsePack(pack,unit,qty=1){const raw=text(pack).toLowerCase().replace(/[×*]/g,'x').replace(/\s+/g,''),fallback=text(unit).toUpperCase();let count=1,size=1,kind=fallback;const multi=raw.match(/^(\d+(?:\.\d+)?)x(\d+(?:\.\d+)?)(kg|g|l|ml|pcs?|btl|pkt)$/);const single=raw.match(/^(\d+(?:\.\d+)?)(kg|g|l|ml|pcs?|btl|pkt)$/);if(multi){count=number(multi[1]);size=number(multi[2]);kind=multi[3].toUpperCase()}else if(single){size=number(single[1]);kind=single[2].toUpperCase()}let base=count*size*number(qty||1);if(kind==='KG')base*=1000;if(kind==='L')base*=1000;const baseUnit=['KG','G'].includes(kind)?'G':['L','ML'].includes(kind)?'ML':'PCS';return{count,size,kind,base,baseUnit}}
function derived(pack,unit,qty,packRate){const parsed=parsePack(pack,unit,qty),lineTotal=number(qty)*number(packRate),perBase=parsed.base?lineTotal/parsed.base:0;return{...parsed,lineTotal,perBase,perLarge:parsed.baseUnit==='G'?perBase*1000:parsed.baseUnit==='ML'?perBase*1000:perBase}}
function rowTemplate(item={}){const qty=number(get(item,'qty','quantity'))||1,packRate=number(get(item,'pack_rate','rate'))||(qty?number(get(item,'row_total','total'))/qty:0),unit=text(get(item,'unit')).toUpperCase()||'PCS';return `<div class="bill-row"><label class="item-name">Product<input data-field="description" required value="${escapeHtml(get(item,'description','product','name'))}" placeholder="Product name"></label><label>Pack format<input data-field="pack" value="${escapeHtml(get(item,'pack_format','packing')||'')}" placeholder="24x330 ml"></label><label>Unit<select data-field="unit">${units.map(u=>`<option ${unit===u?'selected':''}>${u}</option>`).join('')}</select></label><label>Qty<input data-field="qty" type="number" min="0.001" step="any" value="${qty}"></label><label>Pack rate<input data-field="packRate" type="number" min="0" step="any" value="${packRate||''}" placeholder="MVR"></label><label>GST %<input data-field="gst" type="number" min="0" step="any" value="${number(get(item,'gst'))}"></label><div class="rate-preview"><span data-base>—</span><small data-rates>Enter pack details</small></div><button class="btn danger small remove-row" data-remove type="button" aria-label="Remove row">×</button></div>`}

export function newBillPage(){
  const editing=store.editing;if(editing&&!canEdit(editing)){store.editing=null;alert('Staff can edit a bill only within 24 hours.');location.hash='#bills';return}
  const existing=editing?(Array.isArray(editing.items)&&editing.items.length?editing.items:[itemOf(editing)]):[],vendors=vendorDirectory();
  content().innerHTML=`${header(editing?'Edit Bill':'New Bill',editing?'Update this procurement record.':'Record a supplier purchase with automatic unit rates.','<button class="btn secondary" data-route="bills">Close</button>')}<form id="billForm" class="bill-form"><section class="card"><header class="card-head"><div><h2>Bill information</h2><small>Vendor and bill details</small></div></header><div class="card-body form-grid"><label>Vendor<input id="vendor" list="vendorList" required value="${escapeHtml(editing?vendor(editing):'')}" placeholder="Search or type vendor"><datalist id="vendorList">${vendors.map(v=>`<option value="${escapeHtml(v.name)}"></option>`).join('')}</datalist></label><label>Bill date<input id="date" type="date" required value="${escapeHtml(editing?billDate(editing):today())}"></label><label>Bill no.<input id="billNo" value="${escapeHtml(editing&&billNo(editing)!=='—'?billNo(editing):'')}" placeholder="Optional"></label><label>Vendor TIN<input id="tin" value="${escapeHtml(editing?text(get(editing,'tin','vendor_tin')):'')}" placeholder="Optional"></label><label>Vendor mobile<input id="mobile" value="${escapeHtml(editing?text(get(editing,'mobile','phone','vendor_mobile')):'')}" placeholder="Optional"></label><label>Location<input id="location" value="${escapeHtml(editing?text(get(editing,'location','address')):'')}" placeholder="Optional"></label><label>Payment status<select id="payment"><option ${!editing||status(editing)==='Pending'?'selected':''}>Pending</option><option ${editing&&status(editing)==='Paid'?'selected':''}>Paid</option></select></label><label>Payment method<select id="method"><option value="">Select method</option>${methods.map(m=>`<option ${editing&&text(get(editing,'payment_method','method'))===m?'selected':''}>${m}</option>`).join('')}</select></label><label>Category<input id="category" value="${escapeHtml(editing?text(get(editing,'category')):'')}" placeholder="Auto or manual"></label></div></section><section class="card"><header class="card-head"><div><h2>Bill items</h2><small>Pack and base-unit rates calculate automatically</small></div><button class="btn secondary small" id="addRow" type="button">Add row</button></header><div class="bill-items" id="billItems">${(existing.length?existing:[{}]).map(rowTemplate).join('')}</div></section><section class="card"><div class="card-body bill-footer"><label>Notes<textarea id="notes">${escapeHtml(editing?text(get(editing,'notes')):'')}</textarea></label><div><div class="totals"><div><span>Subtotal</span><strong id="subtotal">MVR 0.00</strong></div><div><span>GST total</span><strong id="gstTotal">MVR 0.00</strong></div><div class="grand"><span>Total due</span><strong id="grandTotal">MVR 0.00</strong></div></div><div class="actions form-actions"><button class="btn" type="submit">Review & save</button><button class="btn secondary" type="button" data-route="bills">Cancel</button></div></div></div></section></form>`;
  const vendorMap=new Map(vendors.map(v=>[v.name.toLowerCase(),v]));$('#vendor').addEventListener('change',()=>{const found=vendorMap.get(text($('#vendor').value).toLowerCase());if(!found)return;if(!text($('#tin').value))$('#tin').value=found.tin;if(!text($('#mobile').value))$('#mobile').value=found.mobile;if(!text($('#location').value))$('#location').value=found.location});
  const items=()=>[...document.querySelectorAll('.bill-row')].map(row=>{const description=text(row.querySelector('[data-field="description"]').value),pack=text(row.querySelector('[data-field="pack"]').value),unit=row.querySelector('[data-field="unit"]').value,qty=number(row.querySelector('[data-field="qty"]').value),packRate=number(row.querySelector('[data-field="packRate"]').value),gst=number(row.querySelector('[data-field="gst"]').value),calc=derived(pack,unit,qty,packRate);return{row,description,pack,unit,qty,packRate,gst,...calc}}).filter(i=>i.description||i.packRate);
  const totals=()=>{const list=items();list.forEach(i=>{i.row.querySelector('[data-base]').textContent=i.base?`${i.base.toLocaleString('en-US')} ${i.baseUnit}`:'—';const small=i.base?`${money(i.perBase)} / ${i.baseUnit}`:'No base rate';const large=i.baseUnit==='G'?`${money(i.perLarge)} / KG`:i.baseUnit==='ML'?`${money(i.perLarge)} / L':`${money(i.perLarge)} / PCS`;i.row.querySelector('[data-rates]').textContent=`${small} · ${large} · Line ${money(i.lineTotal)}`});const sub=list.reduce((s,i)=>s+i.lineTotal,0),gst=list.reduce((s,i)=>s+i.lineTotal*i.gst/100,0);$('#subtotal').textContent=money(sub);$('#gstTotal').textContent=money(gst);$('#grandTotal').textContent=money(sub+gst);return{sub,gst,grand:sub+gst,list}};
  const bindRows=()=>{document.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>{if(document.querySelectorAll('.bill-row').length>1)btn.closest('.bill-row').remove();totals()});document.querySelectorAll('.bill-row input,.bill-row select').forEach(el=>{el.oninput=totals;el.onchange=totals})};
  $('#addRow').onclick=()=>{$('#billItems').insertAdjacentHTML('beforeend',rowTemplate({}));bindRows();totals()};bindRows();totals();bindRoute();
  $('#billForm').onsubmit=e=>{e.preventDefault();const summary=totals();if(!text($('#vendor').value)||!$('#date').value||!summary.list.length||summary.list.some(i=>!i.description||i.qty<=0)){alert('Vendor, bill date, product and quantity are required.');return}showReview(summary)};
  function showReview(summary){const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<section class="modal-card"><header class="card-head"><h2>Review before saving</h2><button class="btn secondary small" data-close>Close</button></header><div class="card-body"><p><strong>${escapeHtml($('#vendor').value)}</strong> · ${escapeHtml($('#date').value)} · ${escapeHtml($('#billNo').value||'No bill number')}</p><div class="table-wrap review-table"><table class="table"><thead><tr><th>Product</th><th>Pack</th><th>Qty</th><th>Base quantity</th><th>Unit rates</th><th>GST</th><th class="num">Line total</th></tr></thead><tbody>${summary.list.map(i=>`<tr><td><strong>${escapeHtml(i.description)}</strong></td><td>${escapeHtml(i.pack||i.unit)}</td><td>${i.qty}</td><td>${i.base.toLocaleString('en-US')} ${i.baseUnit}</td><td>${money(i.perBase)} / ${i.baseUnit}<br><small>${i.baseUnit==='G'?`${money(i.perLarge)} / KG`:i.baseUnit==='ML'?`${money(i.perLarge)} / L`:`${money(i.perLarge)} / PCS`}</small></td><td>${i.gst}%</td><td class="num">${money(i.lineTotal+i.lineTotal*i.gst/100)}</td></tr>`).join('')}</tbody></table></div><div class="totals review-totals"><div><span>Subtotal</span><strong>${money(summary.sub)}</strong></div><div><span>GST</span><strong>${money(summary.gst)}</strong></div><div class="grand"><span>Total due</span><strong>${money(summary.grand)}</strong></div></div><div class="actions review-actions"><button class="btn secondary" data-close>Back to edit</button><button class="btn" data-confirm>Confirm & save</button></div></div></section>`;document.body.appendChild(modal);modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.remove());modal.querySelector('[data-confirm]').onclick=async()=>{const shared={bill_date:$('#date').value,bill_no:text($('#billNo').value),vendor:text($('#vendor').value),payment_status:$('#payment').value,payment_method:text($('#method').value),notes:text($('#notes').value),description:text($('#category').value),tin:text($('#tin').value),mobile:text($('#mobile').value),location:text($('#location').value),category:text($('#category').value)};const itemRecord=i=>({description:i.description,pack_format:i.pack,unit:i.unit,qty:i.qty,pack_rate:i.packRate,row_total:i.lineTotal,gst:i.gst,base_quantity:i.base,base_unit:i.baseUnit,unit_rate:i.perBase,large_unit_rate:i.perLarge});try{modal.querySelector('[data-confirm]').disabled=true;if(editing){const i=summary.list[0];await updateBill(editing.id,{...shared,amount:i.lineTotal+i.lineTotal*i.gst/100,items:[itemRecord(i)]})}else{await saveBillRecords(summary.list.map(i=>({...shared,amount:i.lineTotal+i.lineTotal*i.gst/100,items:[itemRecord(i)]})))}store.editing=null;modal.remove();location.hash='#bills'}catch(error){modal.querySelector('[data-confirm]').disabled=false;alert(error.message)}}}
}

function productData(){const map=new Map();[...store.rows].sort((a,b)=>billDate(a).localeCompare(billDate(b))).forEach(row=>{const name=productOf(row),item=itemOf(row);if(!map.has(name))map.set(name,{name,suppliers:new Set(),records:0,lastPrice:0,pack:'',unit:'',unitRate:0});const p=map.get(name);p.suppliers.add(vendor(row));p.records++;p.lastPrice=amount(row);p.pack=text(get(item,'pack_format','packing'));p.unit=text(get(item,'unit'));p.unitRate=number(get(item,'unit_rate'))});return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
export function productsPage(){const data=productData();content().innerHTML=`${header('Products','Product catalogue generated from saved bill items.')}<section class="toolbar product-toolbar"><input id="productSearch" placeholder="Search products or suppliers"><span>${data.length} products</span></section><section class="catalog" id="catalog">${data.map(p=>`<article class="product-card" data-search="${escapeHtml(`${p.name} ${[...p.suppliers].join(' ')}`.toLowerCase())}"><div class="product-image">📦</div><div class="product-body"><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml([...p.suppliers].slice(0,2).join(', '))}</p><strong>${money(p.lastPrice)}</strong><small>${escapeHtml([p.pack,p.unit].filter(Boolean).join(' · '))}</small></div></article>`).join('')||'<div class="empty">No products available.</div>'}</section>`;$('#productSearch').oninput=e=>document.querySelectorAll('.product-card').forEach(card=>card.hidden=!card.dataset.search.includes(e.target.value.toLowerCase()))}
export function ratesPage(){if(store.role!=='admin'){content().innerHTML=`${header('Price Intelligence','Restricted to administrators.')}<section class="card"><div class="empty">Your account does not have permission to view price intelligence.</div></section>`;return}const data=productData();content().innerHTML=`${header('Price Intelligence','Compare current product and base-unit prices.')}<section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Current price</th><th>Base-unit rate</th><th>Pack</th><th>Suppliers</th><th>Records</th></tr></thead><tbody>${data.map(p=>`<tr><td><strong>${escapeHtml(p.name)}</strong></td><td>${money(p.lastPrice)}</td><td>${p.unitRate?money(p.unitRate):'—'}</td><td>${escapeHtml([p.pack,p.unit].filter(Boolean).join(' · '))}</td><td>${p.suppliers.size}</td><td>${p.records}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No price records.</td></tr>'}</tbody></table></div></section>`}
export function vendorsPage(){const map=new Map();store.rows.forEach(b=>{const n=vendor(b);if(!map.has(n))map.set(n,{name:n,bills:0,total:0,products:new Set(),tin:'',mobile:''});const v=map.get(n);v.bills++;v.total+=amount(b);v.products.add(productOf(b));v.tin||=text(get(b,'tin','vendor_tin'));v.mobile||=text(get(b,'mobile','phone','vendor_mobile'))});const data=[...map.values()].sort((a,b)=>b.total-a.total);content().innerHTML=`${header('Vendors','Supplier directory and procurement performance.')}<section class="catalog">${data.map(v=>`<article class="product-card"><div class="product-image">🏢</div><div class="product-body"><h3>${escapeHtml(v.name)}</h3><p>${v.bills} bills · ${v.products.size} products</p><small>${escapeHtml([v.tin&&`TIN ${v.tin}`,v.mobile].filter(Boolean).join(' · '))}</small><strong>${money(v.total)}</strong></div></article>`).join('')||'<div class="empty">No suppliers.</div>'}</section>`}
export function reportsPage(){const rows=store.rows,total=rows.reduce((s,b)=>s+amount(b),0),suppliers=unique(rows.map(vendor));const months=new Map();rows.forEach(b=>{const key=billDate(b).slice(0,7)||'Unknown';months.set(key,(months.get(key)||0)+amount(b))});const list=[...months.entries()].sort((a,b)=>b[0].localeCompare(a[0])).slice(0,12),max=Math.max(1,...list.map(x=>x[1]));content().innerHTML=`${header('Reports','Management analytics for spend, suppliers, products and tax.')}<section class="grid-4">${kpi('Total procurement',money(total))}${kpi('Bills recorded',rows.length.toLocaleString())}${kpi('Suppliers',suppliers.length.toLocaleString())}${kpi('GST recorded',money(rows.reduce((s,b)=>s+number(get(b,'gst_total','gst')),0)))}</section><section class="card"><header class="card-head"><h2>Spend trend</h2><small>By recorded month</small></header><div class="card-body progress-list">${list.map(([m,v])=>`<div class="progress-row"><span>${escapeHtml(m)}</span><div class="track"><span style="width:${v/max*100}%"></span></div><strong>${money(v)}</strong></div>`).join('')}</div></section>`}
export function settingsPage(){content().innerHTML=`${header('Settings','Configure workspace defaults.')}<section class="card"><header class="card-head"><h2>Workspace</h2></header><div class="card-body form-grid"><label>Business name<input value="White Saffron"></label><label>Currency<input value="MVR" disabled></label><label>Rows per page<select id="rowsPerPage"><option>20</option><option>50</option></select></label></div></section>`;$('#rowsPerPage').value=String(store.pageSize);$('#rowsPerPage').onchange=e=>store.pageSize=number(e.target.value)}
export function adminPage(){content().innerHTML=`${header('Admin & users','Current account and system status.')}<section class="grid-4">${kpi('Role',store.role.toUpperCase())}${kpi('Loaded records',store.rows.length.toLocaleString())}${kpi('Session',store.user?'Active':'Signed out')}${kpi('Database','Supabase','Connected through publishable client')}</section>`}
