import {store,money,escapeHtml,text,number,billDate,vendor,amount,status,productOf,get} from './store.js';

const $=s=>document.querySelector(s);
const content=()=>$('#content');
const META_KEY='bills.vendorMetadata.v1';
const readMeta=()=>{try{return JSON.parse(localStorage.getItem(META_KEY)||'{}')}catch{return{}}};
const writeMeta=value=>localStorage.setItem(META_KEY,JSON.stringify(value));
const clean=value=>text(value).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const digits=value=>text(value).replace(/\D/g,'');
const vendorKey=row=>{const tin=digits(get(row,'tin','vendor_tin'));if(tin)return`tin:${tin}`;const mobile=digits(get(row,'mobile','phone','vendor_mobile'));if(mobile.length>=7)return`mobile:${mobile}`;return`name:${clean(vendor(row))}`};
const initials=name=>name.split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'V';

function buildVendors(){
  const meta=readMeta(),groups=new Map();
  [...store.rows].sort((a,b)=>billDate(a).localeCompare(billDate(b))).forEach(row=>{
    const raw=vendor(row),baseKey=vendorKey(row),assigned=meta.aliasToCanonical?.[clean(raw)],key=assigned||baseKey,override=meta.records?.[key]||{};
    if(!groups.has(key))groups.set(key,{key,name:text(override.name)||raw,aliases:new Set(),tins:new Set(),mobiles:new Set(),locations:new Set(),products:new Set(),bills:0,total:0,paid:0,pending:0,lastDate:'',active:override.active!==false,notes:text(override.notes),rows:[]});
    const item=groups.get(key),value=amount(row),state=status(row).toLowerCase(),date=billDate(row);
    item.aliases.add(raw);const tin=text(get(row,'tin','vendor_tin'));const mobile=text(get(row,'mobile','phone','vendor_mobile'));const location=text(get(row,'location','address'));
    if(tin)item.tins.add(tin);if(mobile)item.mobiles.add(mobile);if(location)item.locations.add(location);item.products.add(productOf(row));item.bills++;item.total+=value;if(state==='paid')item.paid+=value;else item.pending+=value;if(date>item.lastDate)item.lastDate=date;item.rows.push(row);
  });
  return[...groups.values()].map(v=>({...v,average:v.bills?v.total/v.bills:0,possibleDuplicate:v.aliases.size>1||v.tins.size>1||v.mobiles.size>1})).sort((a,b)=>b.total-a.total);
}

export function vendorsPage(){
  const vendors=buildVendors();
  content().innerHTML=`<header class="page-head"><div><h1>Vendors</h1><p>Canonical supplier directory, spend analysis, contact quality and duplicate review.</p></div></header>
  <section class="grid-4"><article class="kpi"><span>Canonical vendors</span><strong>${vendors.length}</strong><small>${vendors.filter(v=>v.active).length} active</small></article><article class="kpi"><span>Total spend</span><strong>${money(vendors.reduce((s,v)=>s+v.total,0))}</strong><small>Across all supplier records</small></article><article class="kpi"><span>Pending value</span><strong>${money(vendors.reduce((s,v)=>s+v.pending,0))}</strong><small>Not marked paid</small></article><article class="kpi"><span>Possible duplicates</span><strong>${vendors.filter(v=>v.possibleDuplicate).length}</strong><small>Review aliases and contacts</small></article></section>
  <section class="toolbar vendor-filters"><input id="vendorSearch" placeholder="Search vendor, alias, TIN, mobile or product"><select id="vendorStatus"><option value="active">Active vendors</option><option value="all">All vendors</option><option value="inactive">Inactive vendors</option></select><select id="vendorDuplicates"><option value="all">All records</option><option value="duplicates">Possible duplicates</option></select><span id="vendorCount"></span></section>
  <section class="vendor-grid" id="vendorGrid"></section>`;
  const draw=()=>{const q=clean($('#vendorSearch').value),state=$('#vendorStatus').value,dup=$('#vendorDuplicates').value;const list=vendors.filter(v=>(!q||clean(`${v.name} ${[...v.aliases].join(' ')} ${[...v.tins].join(' ')} ${[...v.mobiles].join(' ')} ${[...v.products].join(' ')}`).includes(q))&&(state==='all'||(state==='active'?v.active:!v.active))&&(dup==='all'||v.possibleDuplicate));$('#vendorCount').textContent=`${list.length} vendors`;$('#vendorGrid').innerHTML=list.map(v=>`<article class="vendor-card"><div class="vendor-card-head"><div class="vendor-avatar">${escapeHtml(initials(v.name))}</div><div><h3>${escapeHtml(v.name)}</h3><p>${v.bills} bills · ${v.products.size} products</p></div>${v.possibleDuplicate?'<span class="badge pending">Review</span>':''}</div><div class="vendor-contact"><span><b>TIN</b>${escapeHtml([...v.tins][0]||'Not recorded')}</span><span><b>Mobile</b>${escapeHtml([...v.mobiles][0]||'Not recorded')}</span><span><b>Location</b>${escapeHtml([...v.locations][0]||'Not recorded')}</span></div><dl class="vendor-stats"><div><dt>Total spend</dt><dd>${money(v.total)}</dd></div><div><dt>Paid</dt><dd>${money(v.paid)}</dd></div><div><dt>Pending</dt><dd>${money(v.pending)}</dd></div><div><dt>Average bill</dt><dd>${money(v.average)}</dd></div><div><dt>Last purchase</dt><dd>${escapeHtml(v.lastDate||'No date')}</dd></div><div><dt>Aliases</dt><dd>${v.aliases.size}</dd></div></dl><div class="vendor-actions"><button class="btn secondary small" data-vendor-details="${escapeHtml(v.key)}">Details</button>${store.role==='admin'?`<button class="btn secondary small" data-vendor-edit="${escapeHtml(v.key)}">Manage</button>`:''}</div></article>`).join('')||'<div class="empty">No vendors match these filters.</div>';document.querySelectorAll('[data-vendor-details]').forEach(x=>x.onclick=()=>showDetails(vendors.find(v=>v.key===x.dataset.vendorDetails)));document.querySelectorAll('[data-vendor-edit]').forEach(x=>x.onclick=()=>showEdit(vendors.find(v=>v.key===x.dataset.vendorEdit)))};
  $('#vendorSearch').oninput=draw;$('#vendorStatus').onchange=draw;$('#vendorDuplicates').onchange=draw;draw();
  function showDetails(v){const rows=[...v.rows].sort((a,b)=>billDate(b).localeCompare(billDate(a))).slice(0,50),modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<section class="modal-card"><header class="card-head"><div><h2>${escapeHtml(v.name)}</h2><small>${v.bills} bills · ${v.products.size} supplied products</small></div><button class="btn secondary small" data-close>Close</button></header><div class="card-body"><p><strong>Aliases:</strong> ${escapeHtml([...v.aliases].join(', '))}</p><div class="table-wrap vendor-history"><table class="table"><thead><tr><th>Date</th><th>Bill no.</th><th>Product</th><th>Status</th><th class="num">Amount</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(billDate(r)||'No date')}</td><td>${escapeHtml(text(get(r,'bill_no','invoice'))||'—')}</td><td>${escapeHtml(productOf(r))}</td><td>${escapeHtml(status(r))}</td><td class="num"><strong>${money(amount(r))}</strong></td></tr>`).join('')}</tbody></table></div></div></section>`;document.body.appendChild(modal);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()}}
  function showEdit(v){if(store.role!=='admin')return;const all=vendors.filter(x=>x.key!==v.key),modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<section class="modal-card vendor-editor"><header class="card-head"><div><h2>Manage vendor</h2><small>Metadata and alias grouping are saved in this browser.</small></div><button class="btn secondary small" data-close>Close</button></header><form class="card-body form-grid" id="vendorEditForm"><label>Canonical name<input id="vendorName" value="${escapeHtml(v.name)}" required></label><label>Status<select id="vendorActive"><option value="active" ${v.active?'selected':''}>Active</option><option value="inactive" ${!v.active?'selected':''}>Inactive</option></select></label><label>Merge aliases into<select id="vendorMerge"><option value="">Keep as separate vendor</option>${all.map(x=>`<option value="${escapeHtml(x.key)}">${escapeHtml(x.name)}</option>`).join('')}</select></label><label class="vendor-notes">Internal notes<textarea id="vendorNotes">${escapeHtml(v.notes)}</textarea></label><div class="actions vendor-editor-actions"><button class="btn" type="submit">Save vendor</button><button class="btn secondary" type="button" data-close>Cancel</button></div></form></section>`;document.body.appendChild(modal);modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.remove());modal.querySelector('#vendorEditForm').onsubmit=e=>{e.preventDefault();const meta=readMeta();meta.records||={};meta.aliasToCanonical||={};const merge=modal.querySelector('#vendorMerge').value;if(merge){[...v.aliases].forEach(alias=>meta.aliasToCanonical[clean(alias)]=merge)}else{meta.records[v.key]={name:text(modal.querySelector('#vendorName').value),active:modal.querySelector('#vendorActive').value==='active',notes:text(modal.querySelector('#vendorNotes').value)}}writeMeta(meta);modal.remove();vendorsPage()}}
}
