-- BusinessOS v0.2: Purchase Requests + Purchase Orders
-- Applied to Supabase project tmupbruwmwlrmewhoodn on 2026-08-12.

create table if not exists public.purchase_requests (
  id bigint generated by default as identity primary key,
  request_no text not null unique,
  request_date date not null default current_date,
  needed_by date,
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  status text not null default 'draft' check (status in ('draft','submitted','approved','rejected','ordered','cancelled')),
  requested_by uuid not null references auth.users(id) on delete restrict,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  decision_note text,
  notes text,
  estimated_total numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchase_request_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.purchase_requests(id) on delete cascade,
  supply_id bigint not null references public.supply(id) on delete restrict,
  description text not null,
  quantity numeric(14,4) not null check (quantity > 0),
  unit text not null,
  estimated_unit_cost numeric(14,4) not null default 0 check (estimated_unit_cost >= 0),
  preferred_vendor_id uuid references public.vendors(id) on delete set null,
  notes text,
  sort_order integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  po_no text not null unique,
  request_id bigint references public.purchase_requests(id) on delete set null,
  vendor_id uuid not null references public.vendors(id) on delete restrict,
  order_date date not null default current_date,
  expected_date date,
  status text not null default 'draft' check (status in ('draft','approved','sent','part_received','received','cancelled','closed')),
  currency text not null default 'MVR',
  subtotal numeric(14,2) not null default 0,
  gst_total numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  notes text,
  created_by uuid not null references auth.users(id) on delete restrict,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchase_order_items (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete cascade,
  source_request_item_id bigint references public.purchase_request_items(id) on delete set null,
  supply_id bigint not null references public.supply(id) on delete restrict,
  description text not null,
  quantity numeric(14,4) not null check (quantity > 0),
  received_quantity numeric(14,4) not null default 0 check (received_quantity >= 0),
  unit text not null,
  unit_rate numeric(14,4) not null default 0 check (unit_rate >= 0),
  gst_rate numeric(7,4) not null default 0 check (gst_rate >= 0 and gst_rate <= 100),
  line_subtotal numeric(14,2) not null default 0,
  line_gst numeric(14,2) not null default 0,
  line_total numeric(14,2) not null default 0,
  sort_order integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists purchase_requests_status_date_idx on public.purchase_requests(status, request_date desc, id desc);
create index if not exists purchase_requests_requester_idx on public.purchase_requests(requested_by, created_at desc);
create index if not exists purchase_request_items_request_idx on public.purchase_request_items(request_id, sort_order, id);
create index if not exists purchase_request_items_supply_idx on public.purchase_request_items(supply_id);
create index if not exists purchase_orders_status_date_idx on public.purchase_orders(status, order_date desc, id desc);
create index if not exists purchase_orders_vendor_idx on public.purchase_orders(vendor_id, order_date desc);
create index if not exists purchase_orders_request_idx on public.purchase_orders(request_id) where request_id is not null;
create index if not exists purchase_order_items_order_idx on public.purchase_order_items(purchase_order_id, sort_order, id);
create index if not exists purchase_order_items_request_item_idx on public.purchase_order_items(source_request_item_id) where source_request_item_id is not null;

alter table public.purchase_requests enable row level security;
alter table public.purchase_request_items enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;

drop policy if exists purchase_requests_read_active_users on public.purchase_requests;
create policy purchase_requests_read_active_users on public.purchase_requests for select to authenticated
using (exists(select 1 from public.user_roles ur where ur.user_id=auth.uid() and ur.is_active));

drop policy if exists purchase_request_items_read_active_users on public.purchase_request_items;
create policy purchase_request_items_read_active_users on public.purchase_request_items for select to authenticated
using (exists(select 1 from public.user_roles ur where ur.user_id=auth.uid() and ur.is_active));

drop policy if exists purchase_orders_read_active_users on public.purchase_orders;
create policy purchase_orders_read_active_users on public.purchase_orders for select to authenticated
using (exists(select 1 from public.user_roles ur where ur.user_id=auth.uid() and ur.is_active));

drop policy if exists purchase_order_items_read_active_users on public.purchase_order_items;
create policy purchase_order_items_read_active_users on public.purchase_order_items for select to authenticated
using (exists(select 1 from public.user_roles ur where ur.user_id=auth.uid() and ur.is_active));

revoke all on public.purchase_requests, public.purchase_request_items, public.purchase_orders, public.purchase_order_items from anon;
revoke insert, update, delete on public.purchase_requests, public.purchase_request_items, public.purchase_orders, public.purchase_order_items from authenticated;
grant select on public.purchase_requests, public.purchase_request_items, public.purchase_orders, public.purchase_order_items to authenticated;

create or replace function public.create_purchase_request(p_request jsonb, p_items jsonb)
returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_uid uuid:=auth.uid();
  v_role text;
  v_id bigint;
  v_item jsonb;
  v_supply_id bigint;
  v_name text;
  v_unit text;
  v_rate numeric;
  v_qty numeric;
  v_est numeric;
  v_vendor uuid;
  v_total numeric:=0;
  v_sort integer:=0;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'') not in ('admin','manager','staff') then raise exception 'Not authorized to create purchase requests'; end if;
  if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'At least one request item is required'; end if;

  insert into public.purchase_requests(request_no,request_date,needed_by,priority,status,requested_by,notes)
  values(
    'PR-TMP-'||gen_random_uuid()::text,
    coalesce(nullif(p_request->>'request_date','')::date,current_date),
    nullif(p_request->>'needed_by','')::date,
    case when lower(coalesce(p_request->>'priority','normal')) in ('low','normal','high','urgent') then lower(coalesce(p_request->>'priority','normal')) else 'normal' end,
    'draft',v_uid,nullif(btrim(coalesce(p_request->>'notes','')),'')
  ) returning id into v_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_sort:=v_sort+1;
    v_supply_id:=nullif(v_item->>'supply_id','')::bigint;
    v_qty:=coalesce(nullif(v_item->>'quantity','')::numeric,0);
    if v_supply_id is null or v_qty<=0 then raise exception 'Every request item requires a valid product and quantity'; end if;
    select "Name",coalesce(nullif("Unit",''),'PCS'),coalesce("Rate",0) into v_name,v_unit,v_rate
      from public.supply where id=v_supply_id and is_active;
    if not found then raise exception 'Product % is unavailable',v_supply_id; end if;
    v_est:=coalesce(nullif(v_item->>'estimated_unit_cost','')::numeric,v_rate,0);
    if v_est<0 then raise exception 'Estimated unit cost cannot be negative'; end if;
    v_vendor:=nullif(v_item->>'preferred_vendor_id','')::uuid;
    if v_vendor is not null and not exists(select 1 from public.vendors where id=v_vendor and is_active and deleted_at is null) then raise exception 'Preferred supplier is unavailable'; end if;
    insert into public.purchase_request_items(request_id,supply_id,description,quantity,unit,estimated_unit_cost,preferred_vendor_id,notes,sort_order)
    values(v_id,v_supply_id,coalesce(nullif(btrim(v_item->>'description'),''),v_name),v_qty,
      coalesce(nullif(btrim(v_item->>'unit'),''),v_unit),v_est,v_vendor,
      nullif(btrim(coalesce(v_item->>'notes','')),''),v_sort);
    v_total:=v_total+(v_qty*v_est);
  end loop;

  update public.purchase_requests set request_no='PR-'||extract(year from request_date)::int||'-'||lpad(id::text,6,'0'),estimated_total=round(v_total,2),updated_at=now() where id=v_id;
  return v_id;
end;
$func$;

create or replace function public.submit_purchase_request(p_request_id bigint)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_uid uuid:=auth.uid();
  v_role text;
  v_req public.purchase_requests%rowtype;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'') not in ('admin','manager','staff') then raise exception 'Not authorized'; end if;
  select * into v_req from public.purchase_requests where id=p_request_id for update;
  if not found then raise exception 'Purchase request not found'; end if;
  if v_req.status<>'draft' then raise exception 'Only draft requests can be submitted'; end if;
  if v_req.requested_by<>v_uid and v_role not in ('admin','manager') then raise exception 'You can only submit your own request'; end if;
  update public.purchase_requests set status='submitted',updated_at=now() where id=p_request_id;
end;
$func$;

create or replace function public.review_purchase_request(p_request_id bigint,p_decision text,p_note text default null)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_uid uuid:=auth.uid();
  v_role text;
  v_decision text:=lower(btrim(coalesce(p_decision,'')));
  v_req public.purchase_requests%rowtype;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'') not in ('admin','manager') then raise exception 'Only admin or manager can review purchase requests'; end if;
  if v_decision not in ('approved','rejected') then raise exception 'Decision must be approved or rejected'; end if;
  if v_decision='rejected' and btrim(coalesce(p_note,''))='' then raise exception 'A rejection reason is required'; end if;
  select * into v_req from public.purchase_requests where id=p_request_id for update;
  if not found then raise exception 'Purchase request not found'; end if;
  if v_req.status<>'submitted' then raise exception 'Only submitted requests can be reviewed'; end if;
  update public.purchase_requests
    set status=v_decision,reviewed_by=v_uid,reviewed_at=now(),decision_note=nullif(btrim(coalesce(p_note,'')),''),updated_at=now()
    where id=p_request_id;
end;
$func$;

create or replace function public.create_purchase_order_from_request(
  p_request_id bigint,
  p_vendor_id uuid,
  p_item_ids bigint[],
  p_expected_date date default null,
  p_notes text default null
) returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_uid uuid:=auth.uid();
  v_role text;
  v_req public.purchase_requests%rowtype;
  v_po_id bigint;
  v_item_id bigint;
  v_item public.purchase_request_items%rowtype;
  v_rate numeric;
  v_gst numeric:=8;
  v_currency text:='MVR';
  v_sub numeric:=0;
  v_tax numeric:=0;
  v_line_sub numeric;
  v_line_tax numeric;
  v_sort integer:=0;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'') not in ('admin','manager') then raise exception 'Only admin or manager can create purchase orders'; end if;
  if p_vendor_id is null or not exists(select 1 from public.vendors where id=p_vendor_id and is_active and deleted_at is null) then raise exception 'Select an active supplier'; end if;
  if coalesce(cardinality(p_item_ids),0)=0 then raise exception 'Select at least one request item'; end if;
  select * into v_req from public.purchase_requests where id=p_request_id for update;
  if not found then raise exception 'Purchase request not found'; end if;
  if v_req.status not in ('approved') then raise exception 'Only approved requests can create purchase orders'; end if;

  select coalesce(default_gst,8),coalesce(nullif(currency,''),'MVR') into v_gst,v_currency from public.company_settings limit 1;

  insert into public.purchase_orders(po_no,request_id,vendor_id,order_date,expected_date,status,currency,notes,created_by)
  values('PO-TMP-'||gen_random_uuid()::text,p_request_id,p_vendor_id,current_date,p_expected_date,'draft',v_currency,nullif(btrim(coalesce(p_notes,'')),''),v_uid)
  returning id into v_po_id;

  foreach v_item_id in array p_item_ids
  loop
    select * into v_item from public.purchase_request_items where id=v_item_id and request_id=p_request_id;
    if not found then raise exception 'Request item % does not belong to this request',v_item_id; end if;
    if exists(
      select 1 from public.purchase_order_items poi
      join public.purchase_orders po on po.id=poi.purchase_order_id
      where poi.source_request_item_id=v_item_id and po.status<>'cancelled'
    ) then raise exception 'Request item % is already on a purchase order',v_item_id; end if;
    v_sort:=v_sort+1;
    select coalesce("Rate",0) into v_rate from public.supply where id=v_item.supply_id;
    v_rate:=coalesce(nullif(v_item.estimated_unit_cost,0),v_rate,0);
    v_line_sub:=round(v_item.quantity*v_rate,2);
    v_line_tax:=round(v_line_sub*v_gst/100,2);
    insert into public.purchase_order_items(
      purchase_order_id,source_request_item_id,supply_id,description,quantity,unit,unit_rate,gst_rate,line_subtotal,line_gst,line_total,sort_order
    ) values(
      v_po_id,v_item.id,v_item.supply_id,v_item.description,v_item.quantity,v_item.unit,v_rate,v_gst,v_line_sub,v_line_tax,v_line_sub+v_line_tax,v_sort
    );
    v_sub:=v_sub+v_line_sub;
    v_tax:=v_tax+v_line_tax;
  end loop;

  update public.purchase_orders
    set po_no='PO-'||extract(year from order_date)::int||'-'||lpad(id::text,6,'0'),subtotal=round(v_sub,2),gst_total=round(v_tax,2),total=round(v_sub+v_tax,2),updated_at=now()
    where id=v_po_id;

  if not exists(
    select 1 from public.purchase_request_items pri
    where pri.request_id=p_request_id
      and not exists(
        select 1 from public.purchase_order_items poi
        join public.purchase_orders po on po.id=poi.purchase_order_id
        where poi.source_request_item_id=pri.id and po.status<>'cancelled'
      )
  ) then
    update public.purchase_requests set status='ordered',updated_at=now() where id=p_request_id;
  end if;

  return v_po_id;
end;
$func$;

create or replace function public.set_purchase_order_status(p_order_id bigint,p_status text)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_uid uuid:=auth.uid();
  v_role text;
  v_new text:=lower(btrim(coalesce(p_status,'')));
  v_po public.purchase_orders%rowtype;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'') not in ('admin','manager') then raise exception 'Only admin or manager can change purchase order status'; end if;
  if v_new not in ('approved','sent','cancelled') then raise exception 'Unsupported purchase order status'; end if;
  select * into v_po from public.purchase_orders where id=p_order_id for update;
  if not found then raise exception 'Purchase order not found'; end if;
  if v_new='approved' and v_po.status<>'draft' then raise exception 'Only draft purchase orders can be approved'; end if;
  if v_new='sent' and v_po.status<>'approved' then raise exception 'Only approved purchase orders can be marked sent'; end if;
  if v_new='cancelled' and v_po.status in ('received','closed','cancelled') then raise exception 'This purchase order cannot be cancelled'; end if;

  update public.purchase_orders set
    status=v_new,
    approved_by=case when v_new='approved' then v_uid else approved_by end,
    approved_at=case when v_new='approved' then now() else approved_at end,
    sent_at=case when v_new='sent' then now() else sent_at end,
    updated_at=now()
  where id=p_order_id;

  if v_new='cancelled' and v_po.request_id is not null then
    update public.purchase_requests r set status=case when exists(
      select 1 from public.purchase_request_items pri
      where pri.request_id=r.id
        and not exists(
          select 1 from public.purchase_order_items poi
          join public.purchase_orders po on po.id=poi.purchase_order_id
          where poi.source_request_item_id=pri.id and po.status<>'cancelled'
        )
    ) then 'approved' else 'ordered' end,updated_at=now()
    where r.id=v_po.request_id and r.status in ('approved','ordered');
  end if;
end;
$func$;

revoke all on function public.create_purchase_request(jsonb,jsonb) from public;
revoke all on function public.submit_purchase_request(bigint) from public;
revoke all on function public.review_purchase_request(bigint,text,text) from public;
revoke all on function public.create_purchase_order_from_request(bigint,uuid,bigint[],date,text) from public;
revoke all on function public.set_purchase_order_status(bigint,text) from public;

grant execute on function public.create_purchase_request(jsonb,jsonb) to authenticated;
grant execute on function public.submit_purchase_request(bigint) to authenticated;
grant execute on function public.review_purchase_request(bigint,text,text) to authenticated;
grant execute on function public.create_purchase_order_from_request(bigint,uuid,bigint[],date,text) to authenticated;
grant execute on function public.set_purchase_order_status(bigint,text) to authenticated;
