-- BusinessOS v0.3: Goods Receipts / GRN
-- Adds controlled PO receiving, partial receipts, rejection capture, over-delivery control,
-- PO received quantities, and audited inventory movements.

create sequence if not exists public.goods_receipt_no_seq;

create table if not exists public.goods_receipts (
  id bigint generated by default as identity primary key,
  grn_no text not null unique,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete restrict,
  receipt_date date not null default current_date,
  supplier_delivery_no text,
  location text,
  status text not null default 'posted' check (status in ('posted','voided')),
  notes text,
  created_by uuid not null references auth.users(id) on delete restrict,
  posted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.goods_receipt_items (
  id bigint generated by default as identity primary key,
  goods_receipt_id bigint not null references public.goods_receipts(id) on delete restrict,
  purchase_order_item_id bigint not null references public.purchase_order_items(id) on delete restrict,
  supply_id bigint not null references public.supply(id) on delete restrict,
  description text not null,
  unit text not null,
  ordered_quantity numeric(14,4) not null,
  previously_received numeric(14,4) not null default 0,
  received_quantity numeric(14,4) not null default 0 check (received_quantity >= 0),
  rejected_quantity numeric(14,4) not null default 0 check (rejected_quantity >= 0),
  over_delivery_quantity numeric(14,4) not null default 0 check (over_delivery_quantity >= 0),
  remaining_after numeric(14,4) not null default 0 check (remaining_after >= 0),
  unit_rate numeric(14,4) not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  constraint goods_receipt_items_nonzero check (received_quantity + rejected_quantity > 0),
  constraint goods_receipt_items_one_po_line_per_grn unique(goods_receipt_id,purchase_order_item_id)
);

create index if not exists goods_receipts_po_date_idx on public.goods_receipts(purchase_order_id,receipt_date desc,id desc);
create index if not exists goods_receipts_date_idx on public.goods_receipts(receipt_date desc,id desc);
create index if not exists goods_receipt_items_grn_idx on public.goods_receipt_items(goods_receipt_id,id);
create index if not exists goods_receipt_items_po_item_idx on public.goods_receipt_items(purchase_order_item_id,id);
create index if not exists goods_receipt_items_supply_idx on public.goods_receipt_items(supply_id,id);

alter table public.stock_movements add column if not exists goods_receipt_id bigint references public.goods_receipts(id) on delete set null;
alter table public.stock_movements add column if not exists goods_receipt_item_id bigint references public.goods_receipt_items(id) on delete set null;
create index if not exists stock_movements_goods_receipt_idx on public.stock_movements(goods_receipt_id) where goods_receipt_id is not null;

alter table public.goods_receipts enable row level security;
alter table public.goods_receipt_items enable row level security;

drop policy if exists goods_receipts_read_active_users on public.goods_receipts;
create policy goods_receipts_read_active_users on public.goods_receipts for select to authenticated
using (exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.is_active));

drop policy if exists goods_receipt_items_read_active_users on public.goods_receipt_items;
create policy goods_receipt_items_read_active_users on public.goods_receipt_items for select to authenticated
using (exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.is_active));

grant select on public.goods_receipts,public.goods_receipt_items to authenticated;
revoke insert,update,delete on public.goods_receipts,public.goods_receipt_items from anon,authenticated;

create or replace function public.post_goods_receipt(
  p_order_id bigint,
  p_receipt jsonb,
  p_items jsonb,
  p_allow_over_delivery boolean default false
) returns bigint
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $$
declare
  v_uid uuid:=auth.uid();
  v_role text;
  v_po public.purchase_orders%rowtype;
  v_grn_id bigint;
  v_grn_item_id bigint;
  v_grn_no text;
  v_line jsonb;
  v_item public.purchase_order_items%rowtype;
  v_qty numeric;
  v_rejected numeric;
  v_remaining numeric;
  v_over numeric;
  v_stock numeric;
  v_new_stock numeric;
  v_tracking boolean;
  v_line_count integer:=0;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'') not in ('admin','manager','staff') then raise exception 'Not authorized to post goods receipts'; end if;

  select * into v_po from public.purchase_orders where id=p_order_id for update;
  if not found then raise exception 'Purchase order not found'; end if;
  if v_po.status not in ('sent','part_received') then raise exception 'Only sent or partially received purchase orders can be received'; end if;
  if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'At least one receipt line is required'; end if;

  v_grn_no:='GRN-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('public.goods_receipt_no_seq')::text,6,'0');
  insert into public.goods_receipts(grn_no,purchase_order_id,receipt_date,supplier_delivery_no,location,notes,created_by)
  values(
    v_grn_no,
    p_order_id,
    coalesce(nullif(p_receipt->>'receipt_date','')::date,current_date),
    nullif(btrim(p_receipt->>'supplier_delivery_no'),''),
    nullif(btrim(p_receipt->>'location'),''),
    nullif(btrim(p_receipt->>'notes'),''),
    v_uid
  ) returning id into v_grn_id;

  for v_line in select value from jsonb_array_elements(p_items)
  loop
    v_qty:=coalesce(nullif(v_line->>'received_quantity','')::numeric,0);
    v_rejected:=coalesce(nullif(v_line->>'rejected_quantity','')::numeric,0);
    if v_qty<0 or v_rejected<0 then raise exception 'Received and rejected quantities cannot be negative'; end if;
    if v_qty+v_rejected<=0 then continue; end if;

    select * into v_item from public.purchase_order_items
    where id=(v_line->>'purchase_order_item_id')::bigint and purchase_order_id=p_order_id
    for update;
    if not found then raise exception 'Purchase order item not found or does not belong to this order'; end if;

    v_remaining:=greatest(v_item.quantity-v_item.received_quantity,0);
    v_over:=greatest(v_qty-v_remaining,0);
    if v_over>0 and (not p_allow_over_delivery or v_role='staff') then
      raise exception 'Over-delivery of % % requires manager/admin acceptance',v_over,v_item.unit;
    end if;

    if v_qty>0 then
      select coalesce(stock,0),stock_tracking_active into v_stock,v_tracking
      from public.supply where id=v_item.supply_id and is_active for update;
      if not found then raise exception 'Product % is not active',v_item.description; end if;
      if not coalesce(v_tracking,false) then raise exception 'Initialize stock count before receiving %',v_item.description; end if;
      v_new_stock:=v_stock+v_qty;
    else
      v_stock:=0;
      v_new_stock:=0;
    end if;

    insert into public.goods_receipt_items(
      goods_receipt_id,purchase_order_item_id,supply_id,description,unit,
      ordered_quantity,previously_received,received_quantity,rejected_quantity,
      over_delivery_quantity,remaining_after,unit_rate,notes
    ) values(
      v_grn_id,v_item.id,v_item.supply_id,v_item.description,v_item.unit,
      v_item.quantity,v_item.received_quantity,v_qty,v_rejected,
      v_over,greatest(v_item.quantity-(v_item.received_quantity+v_qty),0),v_item.unit_rate,
      nullif(btrim(v_line->>'notes'),'')
    ) returning id into v_grn_item_id;

    if v_qty>0 then
      update public.supply set
        stock=v_new_stock,
        "Rate"=case when v_item.unit_rate>0 then v_item.unit_rate::double precision else "Rate" end,
        last_purchase_date=coalesce(nullif(p_receipt->>'receipt_date','')::date,current_date),
        updated_at=now()
      where id=v_item.supply_id;

      insert into public.stock_movements(
        supply_id,movement_type,quantity,previous_stock,new_stock,reference,reason,movement_date,created_by,
        goods_receipt_id,goods_receipt_item_id
      ) values(
        v_item.supply_id,'purchase',v_qty,v_stock,v_new_stock,v_grn_no,
        'Goods receipt from '||v_po.po_no,
        coalesce(nullif(p_receipt->>'receipt_date','')::date,current_date),v_uid,
        v_grn_id,v_grn_item_id
      );

      update public.purchase_order_items set received_quantity=received_quantity+v_qty where id=v_item.id;
    end if;

    v_line_count:=v_line_count+1;
  end loop;

  if v_line_count=0 then raise exception 'Enter a received or rejected quantity on at least one line'; end if;

  update public.purchase_orders po set
    status=case when not exists(
      select 1 from public.purchase_order_items i
      where i.purchase_order_id=po.id and i.received_quantity<i.quantity
    ) then 'received' else 'part_received' end,
    updated_at=now()
  where po.id=p_order_id;

  return v_grn_id;
end;
$$;

revoke all on function public.post_goods_receipt(bigint,jsonb,jsonb,boolean) from public,anon;
grant execute on function public.post_goods_receipt(bigint,jsonb,jsonb,boolean) to authenticated;

create or replace function public.set_purchase_order_status(p_order_id bigint, p_status text)
returns void
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $$
declare
  v_uid uuid:=auth.uid();
  v_role text;
  v_new text:=lower(btrim(coalesce(p_status,'')));
  v_po public.purchase_orders%rowtype;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'') not in ('admin','manager') then raise exception 'Only admin or manager can change purchase order status'; end if;
  if v_new not in ('approved','sent','cancelled') then raise exception 'Unsupported purchase order status'; end if;
  select * into v_po from public.purchase_orders where id=p_order_id for update;
  if not found then raise exception 'Purchase order not found'; end if;
  if v_new='approved' and v_po.status<>'draft' then raise exception 'Only draft purchase orders can be approved'; end if;
  if v_new='sent' and v_po.status<>'approved' then raise exception 'Only approved purchase orders can be marked sent'; end if;
  if v_new='cancelled' and v_po.status in ('part_received','received','closed','cancelled') then raise exception 'A received purchase order cannot be cancelled'; end if;

  update public.purchase_orders set
    status=v_new,
    approved_by=case when v_new='approved' then v_uid else approved_by end,
    approved_at=case when v_new='approved' then now() else approved_at end,
    sent_at=case when v_new='sent' then now() else sent_at end,
    updated_at=now()
  where id=p_order_id;

  if v_new='cancelled' and v_po.request_id is not null then
    update public.purchase_requests r set status=case when exists(
      select 1 from public.purchase_request_items pri
      where pri.request_id=r.id
        and not exists(
          select 1 from public.purchase_order_items poi
          join public.purchase_orders po on po.id=poi.purchase_order_id
          where poi.source_request_item_id=pri.id and po.status<>'cancelled'
        )
    ) then 'approved' else 'ordered' end,updated_at=now()
    where r.id=v_po.request_id and r.status in ('approved','ordered');
  end if;
end;
$$;
