-- BusinessOS v0.4: Supplier Quotations + admin-only purchase invoice linkage
-- Additive migration. Existing purchase requests, orders, receipts and invoices are unchanged.

create table if not exists public.supplier_quotations (
  id bigint generated by default as identity primary key,
  quotation_no text not null unique,
  supplier_reference text,
  request_id bigint references public.purchase_requests(id) on delete set null,
  vendor_id uuid not null references public.vendors(id) on delete restrict,
  quote_date date not null default current_date,
  valid_until date,
  status text not null default 'draft' check (status in ('draft','final','cancelled')),
  purchase_status text not null default 'not_purchased' check (purchase_status in ('not_purchased','purchased')),
  currency text not null default 'MVR',
  total numeric(14,2) not null default 0 check (total >= 0),
  notes text,
  created_by uuid not null references auth.users(id) on delete restrict,
  finalized_by uuid references auth.users(id) on delete set null,
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quotation_bill_links (
  id bigint generated by default as identity primary key,
  quotation_id bigint not null references public.supplier_quotations(id) on delete cascade,
  bill_id bigint not null references public.bills(id) on delete restrict,
  linked_by uuid not null references auth.users(id) on delete restrict,
  linked_at timestamptz not null default now(),
  unique (quotation_id, bill_id)
);

create index if not exists supplier_quotations_date_idx on public.supplier_quotations(quote_date desc, id desc);
create index if not exists supplier_quotations_vendor_idx on public.supplier_quotations(vendor_id, quote_date desc);
create index if not exists supplier_quotations_request_idx on public.supplier_quotations(request_id) where request_id is not null;
create unique index if not exists supplier_quotations_one_final_per_request_idx
  on public.supplier_quotations(request_id)
  where request_id is not null and status='final';
create index if not exists quotation_bill_links_quote_idx on public.quotation_bill_links(quotation_id, linked_at desc);
create index if not exists quotation_bill_links_bill_idx on public.quotation_bill_links(bill_id);

alter table public.supplier_quotations enable row level security;
alter table public.quotation_bill_links enable row level security;

drop policy if exists supplier_quotations_read_active_users on public.supplier_quotations;
create policy supplier_quotations_read_active_users on public.supplier_quotations
for select to authenticated
using (exists(
  select 1 from public.user_roles ur
  where ur.user_id=auth.uid() and ur.is_active
));

drop policy if exists quotation_bill_links_admin_read on public.quotation_bill_links;
create policy quotation_bill_links_admin_read on public.quotation_bill_links
for select to authenticated
using (exists(
  select 1 from public.user_roles ur
  where ur.user_id=auth.uid() and ur.is_active and lower(ur.role)='admin'
));

revoke all on public.supplier_quotations, public.quotation_bill_links from anon;
revoke insert, update, delete on public.supplier_quotations, public.quotation_bill_links from authenticated;
grant select on public.supplier_quotations, public.quotation_bill_links to authenticated;

create or replace function public.create_supplier_quotation(p_quote jsonb)
returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_uid uuid:=auth.uid();
  v_role text;
  v_id bigint;
  v_vendor uuid;
  v_request bigint;
  v_date date;
  v_total numeric;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'') not in ('admin','manager','staff') then raise exception 'Not authorized to create supplier quotations'; end if;

  v_vendor:=nullif(p_quote->>'vendor_id','')::uuid;
  v_request:=nullif(p_quote->>'request_id','')::bigint;
  v_date:=coalesce(nullif(p_quote->>'quote_date','')::date,current_date);
  v_total:=coalesce(nullif(p_quote->>'total','')::numeric,0);

  if v_vendor is null or not exists(select 1 from public.vendors where id=v_vendor and is_active and deleted_at is null)
    then raise exception 'Select an active supplier'; end if;
  if v_request is not null and not exists(select 1 from public.purchase_requests where id=v_request)
    then raise exception 'Purchase request not found'; end if;
  if v_total < 0 then raise exception 'Quotation total cannot be negative'; end if;

  insert into public.supplier_quotations(
    quotation_no,supplier_reference,request_id,vendor_id,quote_date,valid_until,status,purchase_status,currency,total,notes,created_by
  ) values (
    'Q-TMP-'||gen_random_uuid()::text,
    nullif(btrim(coalesce(p_quote->>'supplier_reference','')),''),
    v_request,
    v_vendor,
    v_date,
    nullif(p_quote->>'valid_until','')::date,
    'draft','not_purchased',
    coalesce(nullif(btrim(coalesce(p_quote->>'currency','')),''),'MVR'),
    round(v_total,2),
    nullif(btrim(coalesce(p_quote->>'notes','')),''),
    v_uid
  ) returning id into v_id;

  update public.supplier_quotations
    set quotation_no='Q-'||extract(year from quote_date)::int||'-'||lpad(id::text,6,'0'), updated_at=now()
    where id=v_id;

  return v_id;
end;
$func$;

create or replace function public.set_supplier_quotation_status(p_quotation_id bigint,p_status text)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_uid uuid:=auth.uid();
  v_role text;
  v_status text:=lower(btrim(coalesce(p_status,'')));
  v_quote public.supplier_quotations%rowtype;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'') not in ('admin','manager') then raise exception 'Only admin or manager can finalize quotations'; end if;
  if v_status not in ('final','cancelled') then raise exception 'Status must be final or cancelled'; end if;

  select * into v_quote from public.supplier_quotations where id=p_quotation_id for update;
  if not found then raise exception 'Supplier quotation not found'; end if;
  if v_quote.status<>'draft' then raise exception 'Only draft quotations can be finalized or cancelled'; end if;

  if v_status='final' then
    update public.supplier_quotations
      set status='final',finalized_by=v_uid,finalized_at=now(),updated_at=now()
      where id=p_quotation_id;
  else
    update public.supplier_quotations
      set status='cancelled',updated_at=now()
      where id=p_quotation_id;
  end if;
end;
$func$;

create or replace function public.link_quotation_bill(p_quotation_id bigint,p_bill_id bigint)
returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_uid uuid:=auth.uid();
  v_role text;
  v_quote public.supplier_quotations%rowtype;
  v_bill public.bills%rowtype;
  v_link_id bigint;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'')<>'admin' then raise exception 'Only admin can link purchase invoices to quotations'; end if;

  select * into v_quote from public.supplier_quotations where id=p_quotation_id for update;
  if not found then raise exception 'Supplier quotation not found'; end if;
  if v_quote.status<>'final' then raise exception 'Only a final quotation can be linked to a purchase invoice'; end if;

  select * into v_bill from public.bills where id=p_bill_id and deleted_at is null;
  if not found then raise exception 'Purchase invoice not found'; end if;
  if v_bill.vendor_id is not null and v_bill.vendor_id<>v_quote.vendor_id then
    raise exception 'Purchase invoice supplier does not match the quotation supplier';
  end if;

  insert into public.quotation_bill_links(quotation_id,bill_id,linked_by)
  values(p_quotation_id,p_bill_id,v_uid)
  on conflict (quotation_id,bill_id) do update set linked_by=excluded.linked_by,linked_at=now()
  returning id into v_link_id;

  update public.supplier_quotations set purchase_status='purchased',updated_at=now() where id=p_quotation_id;
  return v_link_id;
end;
$func$;

create or replace function public.unlink_quotation_bill(p_quotation_id bigint,p_bill_id bigint)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_uid uuid:=auth.uid();
  v_role text;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select lower(role) into v_role from public.user_roles where user_id=v_uid and is_active limit 1;
  if coalesce(v_role,'')<>'admin' then raise exception 'Only admin can unlink purchase invoices from quotations'; end if;

  delete from public.quotation_bill_links where quotation_id=p_quotation_id and bill_id=p_bill_id;
  if not exists(select 1 from public.quotation_bill_links where quotation_id=p_quotation_id) then
    update public.supplier_quotations set purchase_status='not_purchased',updated_at=now() where id=p_quotation_id;
  end if;
end;
$func$;

revoke all on function public.create_supplier_quotation(jsonb) from public,anon;
revoke all on function public.set_supplier_quotation_status(bigint,text) from public,anon;
revoke all on function public.link_quotation_bill(bigint,bigint) from public,anon;
revoke all on function public.unlink_quotation_bill(bigint,bigint) from public,anon;
grant execute on function public.create_supplier_quotation(jsonb) to authenticated;
grant execute on function public.set_supplier_quotation_status(bigint,text) to authenticated;
grant execute on function public.link_quotation_bill(bigint,bigint) to authenticated;
grant execute on function public.unlink_quotation_bill(bigint,bigint) to authenticated;
